/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Control_Clientes;
import Modelo.Cliente;
import java.sql.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mark-
 */
public class FRM_Cliente extends javax.swing.JInternalFrame {
    Control_Clientes crc=new Control_Clientes();
    
    int codCliente;
    
    private int filaC=-1;
    
    private int sswitchC=0;
    
    DefaultTableModel tablaC=new DefaultTableModel();
    
    
    
    public void LlenarTablaCliente(String dato){
    tablaC.setColumnCount(0);
        tablaC.addColumn("Codigo");
        tablaC.addColumn("Rut");
        tablaC.addColumn("Nombre Completo");
        tablaC.addColumn("Fecha de Nacimiento");
        tablaC.addColumn("Direccion 1");
        tablaC.addColumn("Direccion 2");
        tablaC.addColumn("Celular");
        tablaC.addColumn("Telefono Fijo");
        tablaC.addColumn("Correo");        
        List<Cliente> lista=crc.ListaClientes(dato);
        tablaC.setNumRows(lista.size());
        RegistrosClientes1.setText("CLIENTES ALMACENADOS= "+lista.size());
        for (int i = 0; i < lista.size(); i++) {
            tablaC.setValueAt(lista.get(i).getCod_cliente(), i, 0);
            tablaC.setValueAt(lista.get(i).getRut_cliente(), i, 1);
            tablaC.setValueAt(lista.get(i).getNom_cliente(), i, 2);
            tablaC.setValueAt(lista.get(i).getFecn_cliente(), i, 3);
            tablaC.setValueAt(lista.get(i).getDirec1_cliente(), i, 4);
            
            if (lista.get(i).getDirec2_cliente().toString().equalsIgnoreCase("null")) {
                tablaC.setValueAt("------------------------------------", i, 5);
            }else if (lista.get(i).getDirec2_cliente().toString().equalsIgnoreCase("")) {
                tablaC.setValueAt("------------------------------------", i, 5);
            }else{
                tablaC.setValueAt(lista.get(i).getDirec2_cliente(), i, 5);
            }
            
            tablaC.setValueAt(lista.get(i).getTel1_cliente(), i, 6);
            
            if (lista.get(i).getTel2_cliente().toString().equalsIgnoreCase("null")) {
                tablaC.setValueAt("------------------------------------", i, 7);
            }else if (lista.get(i).getTel2_cliente().toString().equalsIgnoreCase("")) {
                tablaC.setValueAt("------------------------------------", i, 7);
            }else{
                tablaC.setValueAt(lista.get(i).getTel2_cliente(), i, 7);
            }
            tablaC.setValueAt(lista.get(i).getCo_cliente(), i, 8);
        }
        
        TablaClientes.setModel(tablaC);
        TablaClientes.getColumnModel().getColumn(0).setMaxWidth(0);
        TablaClientes.getColumnModel().getColumn(0).setMinWidth(0);
        TablaClientes.getColumnModel().getColumn(0).setPreferredWidth(0);
    }
    public FRM_Cliente() {
        initComponents();
        LlenarTablaCliente("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelClientes = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jToolBar13 = new javax.swing.JToolBar();
        RegistrosClientes1 = new javax.swing.JLabel();
        jToolBar16 = new javax.swing.JToolBar();
        AgregarCliente = new javax.swing.JButton();
        jSeparator54 = new javax.swing.JToolBar.Separator();
        jSeparator55 = new javax.swing.JToolBar.Separator();
        jLabel51 = new javax.swing.JLabel();
        jSeparator56 = new javax.swing.JToolBar.Separator();
        jLabel3 = new javax.swing.JLabel();
        BuscadorCliente = new javax.swing.JTextField();
        jSeparator58 = new javax.swing.JToolBar.Separator();
        jScrollPane10 = new javax.swing.JScrollPane();
        TablaClientes = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        GuardarCliente = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        RutCliente = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        NombreCliente = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        Dir1Cliente = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        Dir2Cliente = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        Tel1Cliente = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        Tel2Cliente = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        CorreoCliente = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        FechaCliente = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 102));
        setClosable(true);

        PanelClientes.setBackground(new java.awt.Color(153, 153, 153));
        PanelClientes.setForeground(new java.awt.Color(0, 0, 0));
        PanelClientes.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        PanelClientes.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jPanel1.setLayout(new java.awt.BorderLayout());

        jToolBar13.setBackground(new java.awt.Color(204, 204, 204));
        jToolBar13.setFloatable(false);
        jToolBar13.setForeground(new java.awt.Color(204, 204, 204));
        jToolBar13.setRollover(true);

        RegistrosClientes1.setForeground(new java.awt.Color(0, 0, 0));
        RegistrosClientes1.setText("jLabel5");
        jToolBar13.add(RegistrosClientes1);

        jPanel1.add(jToolBar13, java.awt.BorderLayout.PAGE_START);

        jToolBar16.setBackground(new java.awt.Color(204, 204, 204));
        jToolBar16.setFloatable(false);
        jToolBar16.setRollover(true);

        AgregarCliente.setBackground(new java.awt.Color(153, 153, 153));
        AgregarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cliente.png"))); // NOI18N
        AgregarCliente.setFocusable(false);
        AgregarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AgregarCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarClienteActionPerformed(evt);
            }
        });
        jToolBar16.add(AgregarCliente);
        jToolBar16.add(jSeparator54);
        jToolBar16.add(jSeparator55);
        jToolBar16.add(jLabel51);
        jToolBar16.add(jSeparator56);

        jLabel3.setText("                                                                                          ");
        jToolBar16.add(jLabel3);

        BuscadorCliente.setBackground(new java.awt.Color(70, 110, 196));
        BuscadorCliente.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BuscadorCliente.setForeground(new java.awt.Color(0, 0, 0));
        BuscadorCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BuscadorCliente.setText("Buscador");
        BuscadorCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscadorClienteMouseClicked(evt);
            }
        });
        BuscadorCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BuscadorClienteKeyTyped(evt);
            }
        });
        jToolBar16.add(BuscadorCliente);
        jToolBar16.add(jSeparator58);

        jPanel1.add(jToolBar16, java.awt.BorderLayout.PAGE_END);

        TablaClientes.setBackground(new java.awt.Color(204, 204, 204));
        TablaClientes.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        TablaClientes.setForeground(new java.awt.Color(0, 0, 0));
        TablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaClientes.setMinimumSize(new java.awt.Dimension(60, 100));
        TablaClientes.setName(""); // NOI18N
        TablaClientes.setRowHeight(30);
        TablaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaClientesMouseClicked(evt);
            }
        });
        jScrollPane10.setViewportView(TablaClientes);

        jPanel1.add(jScrollPane10, java.awt.BorderLayout.CENTER);

        PanelClientes.addTab("Lista de Clientes", jPanel1);

        jPanel11.setBackground(new java.awt.Color(153, 153, 153));

        jLabel46.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(0, 0, 0));
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("Agregar Cliente@");

        GuardarCliente.setBackground(new java.awt.Color(204, 204, 204));
        GuardarCliente.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        GuardarCliente.setText("Guardar Datos");
        GuardarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarClienteActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Rut:");

        RutCliente.setBackground(new java.awt.Color(70, 110, 196));
        RutCliente.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        RutCliente.setForeground(new java.awt.Color(0, 0, 0));
        RutCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel39.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 0, 0));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("Nombre Completo:");

        NombreCliente.setBackground(new java.awt.Color(70, 110, 196));
        NombreCliente.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        NombreCliente.setForeground(new java.awt.Color(0, 0, 0));
        NombreCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel40.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 0, 0));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("Direccion 2:");

        Dir1Cliente.setBackground(new java.awt.Color(70, 110, 196));
        Dir1Cliente.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Dir1Cliente.setForeground(new java.awt.Color(0, 0, 0));
        Dir1Cliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel41.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 0, 0));
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("Direccion 1:");

        Dir2Cliente.setBackground(new java.awt.Color(70, 110, 196));
        Dir2Cliente.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Dir2Cliente.setForeground(new java.awt.Color(0, 0, 0));
        Dir2Cliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel42.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 0, 0));
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("Telefono 1:");

        Tel1Cliente.setBackground(new java.awt.Color(70, 110, 196));
        Tel1Cliente.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Tel1Cliente.setForeground(new java.awt.Color(0, 0, 0));
        Tel1Cliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel43.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 0, 0));
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("Telefono 2:");

        Tel2Cliente.setBackground(new java.awt.Color(70, 110, 196));
        Tel2Cliente.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Tel2Cliente.setForeground(new java.awt.Color(0, 0, 0));
        Tel2Cliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel44.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 0, 0));
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("Correo:");

        CorreoCliente.setBackground(new java.awt.Color(70, 110, 196));
        CorreoCliente.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CorreoCliente.setForeground(new java.awt.Color(0, 0, 0));
        CorreoCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel47.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(0, 0, 0));
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("Fecha de Nacimiento:");

        FechaCliente.setBackground(new java.awt.Color(70, 110, 196));
        FechaCliente.setForeground(new java.awt.Color(0, 0, 0));
        try {
            FechaCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        FechaCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FechaCliente.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("(YYYY/MM/DD)");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap(126, Short.MAX_VALUE)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel44)
                                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel42)
                                        .addComponent(jLabel40)
                                        .addComponent(jLabel43)
                                        .addComponent(jLabel41)))
                                .addGap(23, 23, 23))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel47)
                                    .addComponent(jLabel39))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(RutCliente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NombreCliente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Dir1Cliente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Dir2Cliente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tel1Cliente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tel2Cliente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CorreoCliente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FechaCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 294, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(GuardarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel46, javax.swing.GroupLayout.DEFAULT_SIZE, 1129, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RutCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addGap(32, 32, 32)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(4, 4, 4)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(FechaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dir1Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41))
                .addGap(32, 32, 32)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dir2Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40))
                .addGap(32, 32, 32)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(Tel1Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(Tel2Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(CorreoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(GuardarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(621, Short.MAX_VALUE)))
        );

        PanelClientes.addTab("Gestión de Clientes", jPanel11);

        getContentPane().add(PanelClientes, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarClienteActionPerformed
        sswitchC=0;
        PanelClientes.setSelectedIndex(1);
        RutCliente.grabFocus();
    }//GEN-LAST:event_AgregarClienteActionPerformed

    private void BuscadorClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscadorClienteMouseClicked
        BuscadorCliente.setText("");
    }//GEN-LAST:event_BuscadorClienteMouseClicked

    private void BuscadorClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscadorClienteKeyTyped
        LlenarTablaCliente(BuscadorCliente.getText());
    }//GEN-LAST:event_BuscadorClienteKeyTyped

    private void TablaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaClientesMouseClicked
        filaC=TablaClientes.rowAtPoint(evt.getPoint());
    }//GEN-LAST:event_TablaClientesMouseClicked

    private void GuardarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarClienteActionPerformed
        if (RutCliente.getText().equals("") || NombreCliente.getText().equals("") || FechaCliente.getText().equals("")  || Dir1Cliente.getText().equals("")
            ||   Tel1Cliente.getText().equals("") || CorreoCliente.getText().equals("") ){
            JOptionPane.showMessageDialog(this, "DEBE INGRESAR TODOS LOS DATOS!!!", "La biblioteca",JOptionPane.OK_OPTION+JOptionPane.INFORMATION_MESSAGE);
        }else{
            crc.InsertarClientes(RutCliente.getText(), NombreCliente.getText(), Dir1Cliente.getText(),
                Dir2Cliente.getText(), Tel1Cliente.getText(), Tel2Cliente.getText(),CorreoCliente.getText(), Date.valueOf(FechaCliente.getText()));
        }
        RutCliente.setText("");
        NombreCliente.setText("");
        Dir1Cliente.setText("");
        Dir2Cliente.setText("");
        Tel1Cliente.setText("");
        Tel2Cliente.setText("");
        CorreoCliente.setText("");
        FechaCliente.setText("");
        LlenarTablaCliente("");
        PanelClientes.setSelectedIndex(0);
        JOptionPane.showMessageDialog(this, "OPERACION REALIZADA", "LA BIBLIOTECA",JOptionPane.OK_OPTION+JOptionPane.INFORMATION_MESSAGE);
        sswitchC=0;
    }//GEN-LAST:event_GuardarClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarCliente;
    private javax.swing.JTextField BuscadorCliente;
    private javax.swing.JTextField CorreoCliente;
    private javax.swing.JTextField Dir1Cliente;
    private javax.swing.JTextField Dir2Cliente;
    private javax.swing.JFormattedTextField FechaCliente;
    private javax.swing.JButton GuardarCliente;
    private javax.swing.JTextField NombreCliente;
    private javax.swing.JTabbedPane PanelClientes;
    private javax.swing.JLabel RegistrosClientes1;
    private javax.swing.JTextField RutCliente;
    private javax.swing.JTable TablaClientes;
    private javax.swing.JTextField Tel1Cliente;
    private javax.swing.JTextField Tel2Cliente;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JToolBar.Separator jSeparator54;
    private javax.swing.JToolBar.Separator jSeparator55;
    private javax.swing.JToolBar.Separator jSeparator56;
    private javax.swing.JToolBar.Separator jSeparator58;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JToolBar jToolBar13;
    private javax.swing.JToolBar jToolBar16;
    // End of variables declaration//GEN-END:variables
}
