/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Control_AutorLibro;
import Controlador.Control_IdiomaLibro;
import Modelo.Idioma;
import Modelo.IdiomaLibro;
import Modelo.Libros;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mark-
 */
public class FRM_Idiomas extends javax.swing.JInternalFrame {
    Control_IdiomaLibro cri=new Control_IdiomaLibro();
    DefaultTableModel tabla=new DefaultTableModel();
    
    //llenar tabla de idiomas en libros
    public void LlenarTablaIdiomaLibro(String dato){
    tabla.setColumnCount(0);
        tabla.addColumn("Idioma");
        tabla.addColumn("ISBN de Libro");
        tabla.addColumn("Titulo de Libro");
        tabla.addColumn("Numero de Paginas");
        tabla.addColumn("Precio de Libro");
        List<IdiomaLibro> lista=cri.ListarIdiomaLibro(dato);
        tabla.setNumRows(lista.size());
        for (int i = 0; i < lista.size(); i++) {
            tabla.setValueAt(lista.get(i).getNom_idioma(), i, 0);
            tabla.setValueAt(lista.get(i).getIsbn_libro(), i, 1);
            tabla.setValueAt(lista.get(i).getTitulo_libro(), i, 2);
            tabla.setValueAt(lista.get(i).getPag_libro(), i, 3);
            tabla.setValueAt(lista.get(i).getPrecio_libro(), i, 4);
        }
       TablaIdiomas.setModel(tabla);
    }
    
    //COMBOBOX PARA GESTION DE IDIOMAS EN LIBROS
    private void ComboIdioma(){
       DefaultComboBoxModel combo = new DefaultComboBoxModel();
        Control_IdiomaLibro cil=new Control_IdiomaLibro();
        List<Idioma> lista=cil.ComboBoxIdiomas();
        for(Idioma I:lista){
            I = new Idioma(I.getCod_idioma(), I.getNom_idioma());
            combo.addElement(I);
        }
        Cidioma.setModel(combo);
    }
    
    private void ComboLibros(){
       DefaultComboBoxModel combo = new DefaultComboBoxModel();
        Control_AutorLibro ca=new Control_AutorLibro();
        List<Libros> lista=ca.ComboBoxLibros();
        for(Libros L:lista){
            L = new Libros(L.getCod_libro(), L.getTitulo_libro());
            combo.addElement(L);
        }
        ComboLibro.setModel(combo);
    }
    
    
    public FRM_Idiomas() {
        initComponents();
        LlenarTablaIdiomaLibro("");
        ComboLibros();
        ComboIdioma();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelIdiomas = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jToolBar12 = new javax.swing.JToolBar();
        RegistrosI = new javax.swing.JLabel();
        jToolBar10 = new javax.swing.JToolBar();
        AgregarIdioma = new javax.swing.JButton();
        jSeparator36 = new javax.swing.JToolBar.Separator();
        jSeparator37 = new javax.swing.JToolBar.Separator();
        jLabel40 = new javax.swing.JLabel();
        jSeparator38 = new javax.swing.JToolBar.Separator();
        jSeparator41 = new javax.swing.JToolBar.Separator();
        BuscadorIdioma = new javax.swing.JTextField();
        jSeparator42 = new javax.swing.JToolBar.Separator();
        jScrollPane5 = new javax.swing.JScrollPane();
        TablaIdiomas = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        ComboLibro = new javax.swing.JComboBox();
        jLabel50 = new javax.swing.JLabel();
        Cidioma = new javax.swing.JComboBox();
        GuardarIdiomaLibro1 = new javax.swing.JButton();

        setClosable(true);

        PanelIdiomas.setBackground(new java.awt.Color(153, 153, 153));
        PanelIdiomas.setForeground(new java.awt.Color(0, 0, 0));
        PanelIdiomas.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        PanelIdiomas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jPanel1.setLayout(new java.awt.BorderLayout());

        jToolBar12.setBackground(new java.awt.Color(204, 204, 204));
        jToolBar12.setFloatable(false);
        jToolBar12.setForeground(new java.awt.Color(204, 204, 204));
        jToolBar12.setRollover(true);

        RegistrosI.setForeground(new java.awt.Color(0, 0, 0));
        RegistrosI.setText("jLabel5");
        jToolBar12.add(RegistrosI);

        jPanel1.add(jToolBar12, java.awt.BorderLayout.PAGE_START);

        jToolBar10.setBackground(new java.awt.Color(204, 204, 204));
        jToolBar10.setFloatable(false);
        jToolBar10.setRollover(true);

        AgregarIdioma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/matematicas.png"))); // NOI18N
        AgregarIdioma.setFocusable(false);
        AgregarIdioma.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AgregarIdioma.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AgregarIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarIdiomaActionPerformed(evt);
            }
        });
        jToolBar10.add(AgregarIdioma);
        jToolBar10.add(jSeparator36);
        jToolBar10.add(jSeparator37);

        jLabel40.setText("                                            ");
        jToolBar10.add(jLabel40);
        jToolBar10.add(jSeparator38);
        jToolBar10.add(jSeparator41);

        BuscadorIdioma.setBackground(new java.awt.Color(70, 110, 196));
        BuscadorIdioma.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BuscadorIdioma.setForeground(new java.awt.Color(0, 0, 0));
        BuscadorIdioma.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BuscadorIdioma.setText("Buscador");
        BuscadorIdioma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscadorIdiomaMouseClicked(evt);
            }
        });
        BuscadorIdioma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BuscadorIdiomaKeyTyped(evt);
            }
        });
        jToolBar10.add(BuscadorIdioma);
        jToolBar10.add(jSeparator42);

        jPanel1.add(jToolBar10, java.awt.BorderLayout.PAGE_END);

        TablaIdiomas.setBackground(new java.awt.Color(204, 204, 204));
        TablaIdiomas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        TablaIdiomas.setForeground(new java.awt.Color(0, 0, 0));
        TablaIdiomas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaIdiomas.setRowHeight(25);
        jScrollPane5.setViewportView(TablaIdiomas);

        jPanel1.add(jScrollPane5, java.awt.BorderLayout.CENTER);

        PanelIdiomas.addTab("Idiomas en Libros", jPanel1);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel49.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(0, 0, 0));
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("Titulo de Libro:");

        ComboLibro.setBackground(new java.awt.Color(70, 110, 196));
        ComboLibro.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ComboLibro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel50.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(0, 0, 0));
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setText("Idiomas Disponible:");

        Cidioma.setBackground(new java.awt.Color(70, 110, 196));
        Cidioma.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Cidioma.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        GuardarIdiomaLibro1.setBackground(new java.awt.Color(204, 204, 204));
        GuardarIdiomaLibro1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        GuardarIdiomaLibro1.setText("Guardar");
        GuardarIdiomaLibro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarIdiomaLibro1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel49, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel50, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ComboLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(Cidioma, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(GuardarIdiomaLibro1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel49)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ComboLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel50)
                .addGap(18, 18, 18)
                .addComponent(Cidioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(GuardarIdiomaLibro1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        PanelIdiomas.addTab("Gestion", jPanel2);

        getContentPane().add(PanelIdiomas, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarIdiomaActionPerformed

        PanelIdiomas.setSelectedIndex(1);
    }//GEN-LAST:event_AgregarIdiomaActionPerformed

    private void BuscadorIdiomaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscadorIdiomaMouseClicked
        BuscadorIdioma.setText("");
    }//GEN-LAST:event_BuscadorIdiomaMouseClicked

    private void BuscadorIdiomaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscadorIdiomaKeyTyped
        LlenarTablaIdiomaLibro(BuscadorIdioma.getText());
    }//GEN-LAST:event_BuscadorIdiomaKeyTyped

    private void GuardarIdiomaLibro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarIdiomaLibro1ActionPerformed
        Libros lib=(Libros)ComboLibro.getSelectedItem();
        Idioma idi=(Idioma)Cidioma.getSelectedItem();
        cri.InsertarIdiomaLibro(idi.getCod_idioma(), lib.getCod_libro());
        PanelIdiomas.setSelectedIndex(0);
        JOptionPane.showMessageDialog(this, "OPERACION REALIZADA", "LA BIBLIOTECA",JOptionPane.OK_OPTION+JOptionPane.INFORMATION_MESSAGE);
        LlenarTablaIdiomaLibro("");
    }//GEN-LAST:event_GuardarIdiomaLibro1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarIdioma;
    private javax.swing.JTextField BuscadorIdioma;
    private javax.swing.JComboBox Cidioma;
    private javax.swing.JComboBox ComboLibro;
    private javax.swing.JButton GuardarIdiomaLibro1;
    private javax.swing.JTabbedPane PanelIdiomas;
    private javax.swing.JLabel RegistrosI;
    private javax.swing.JTable TablaIdiomas;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JToolBar.Separator jSeparator36;
    private javax.swing.JToolBar.Separator jSeparator37;
    private javax.swing.JToolBar.Separator jSeparator38;
    private javax.swing.JToolBar.Separator jSeparator41;
    private javax.swing.JToolBar.Separator jSeparator42;
    private javax.swing.JToolBar jToolBar10;
    private javax.swing.JToolBar jToolBar12;
    // End of variables declaration//GEN-END:variables
}
