/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Control_Boleta_o_Factura;
import Modelo.BoletaOfactura;
import Modelo.MetodoPago;
import Modelo.NacionAutor;
import Modelo.TipoBF;
import java.sql.Date;
import java.sql.Time;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mark-
 */
public class FRM_Boleta_o_Factura extends javax.swing.JInternalFrame {
    int codBoF;
    private int filaBoF=-1;
    private int sswitch=0;
    Control_Boleta_o_Factura crbf=new Control_Boleta_o_Factura();
    DefaultTableModel tabla=new DefaultTableModel();
    
    public void LlenarTabla(String Dato){
    tabla.setColumnCount(0);
        tabla.addColumn("Codigo");
        tabla.addColumn("Folio");
        tabla.addColumn("Precio Neto");
        tabla.addColumn("Iva");
        tabla.addColumn("Total");
        tabla.addColumn("Fecha/Hora Emitida");
        tabla.addColumn("Tipo");
        tabla.addColumn("Metodo de Pago");
        tabla.addColumn("hora");
        tabla.addColumn("fecha");
        List<BoletaOfactura> lista=crbf.ListarBoF(Dato);
        tabla.setNumRows(lista.size());
        registros.setText("CANTIDAD DE REGISTROS= "+lista.size());
        for (int i = 0; i < lista.size(); i++) {
            tabla.setValueAt(lista.get(i).getCod_bof(), i, 0);
            tabla.setValueAt(lista.get(i).getFolio(), i, 1);
            tabla.setValueAt(lista.get(i).getPrecio_neto(), i, 2);
            tabla.setValueAt(lista.get(i).getCostoiva(), i, 3);
            tabla.setValueAt(lista.get(i).getPrecio_iva(), i, 4);
            tabla.setValueAt(lista.get(i).getFecha()+" / "+lista.get(i).getHora(), i, 5);
            tabla.setValueAt(lista.get(i).getNom_tipobf(), i, 6);
            tabla.setValueAt(lista.get(i).getNom_metod(), i, 7);
            tabla.setValueAt(lista.get(i).getHora(), i, 8);
            tabla.setValueAt(lista.get(i).getFecha(), i, 9);
        }
        TablaBoF.setModel(tabla);
        TablaBoF.getColumnModel().getColumn(0).setMaxWidth(0);
        TablaBoF.getColumnModel().getColumn(0).setMinWidth(0);
        TablaBoF.getColumnModel().getColumn(0).setPreferredWidth(0);
        
        TablaBoF.getColumnModel().getColumn(8).setMaxWidth(0);
        TablaBoF.getColumnModel().getColumn(8).setMinWidth(0);
        TablaBoF.getColumnModel().getColumn(8).setPreferredWidth(0);
        
        TablaBoF.getColumnModel().getColumn(9).setMaxWidth(0);
        TablaBoF.getColumnModel().getColumn(9).setMinWidth(0);
        TablaBoF.getColumnModel().getColumn(9).setPreferredWidth(0);
    }
    
    private void ComboTipo(){
       DefaultComboBoxModel combo = new DefaultComboBoxModel();
        Control_Boleta_o_Factura c=new Control_Boleta_o_Factura();
        List<TipoBF> lista=c.comboBoxTipoBoF();
        for(TipoBF bf:lista){
            bf = new TipoBF(bf.getCod_tipobf(), bf.getNom_tipobf());
            combo.addElement(bf);
        }
        ComboTipo.setModel(combo);
    }
    
    private void ComboMetodo(){
       DefaultComboBoxModel combo = new DefaultComboBoxModel();
        Control_Boleta_o_Factura c=new Control_Boleta_o_Factura();
        List<MetodoPago> lista=c.comboBoxMetodoP();
        for(MetodoPago bf:lista){
            bf = new MetodoPago(bf.getCod_metod(), bf.getNom_metod());
            combo.addElement(bf);
        }
        ComboMetodoP.setModel(combo);
    }
    
    public FRM_Boleta_o_Factura() {
        initComponents();
        LlenarTabla("");
        ComboTipo();
        ComboMetodo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        Panel = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        registros = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        AgregarBoF = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        Editar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jLabel1 = new javax.swing.JLabel();
        Buscador = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        Eliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaBoF = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Folio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Precio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Fecha = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ComboMetodoP = new javax.swing.JComboBox();
        Hora = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ComboTipo = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        Guardar = new javax.swing.JButton();

        jButton4.setText("jButton4");

        setBackground(new java.awt.Color(102, 102, 102));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setClosable(true);
        setForeground(java.awt.Color.white);
        setDoubleBuffered(true);

        Panel.setBackground(new java.awt.Color(153, 153, 153));
        Panel.setForeground(new java.awt.Color(0, 0, 0));
        Panel.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jToolBar2.setBackground(new java.awt.Color(204, 204, 204));
        jToolBar2.setBorder(null);
        jToolBar2.setFloatable(false);
        jToolBar2.setForeground(new java.awt.Color(102, 102, 102));
        jToolBar2.setRollover(true);

        registros.setBackground(new java.awt.Color(0, 0, 0));
        registros.setForeground(new java.awt.Color(0, 0, 0));
        registros.setText("jLabel1");
        jToolBar2.add(registros);

        jPanel1.add(jToolBar2, java.awt.BorderLayout.PAGE_START);

        jToolBar1.setBackground(new java.awt.Color(204, 204, 204));
        jToolBar1.setBorder(null);
        jToolBar1.setFloatable(false);
        jToolBar1.setForeground(new java.awt.Color(204, 204, 204));
        jToolBar1.setRollover(true);

        AgregarBoF.setText("Agregar");
        AgregarBoF.setFocusable(false);
        AgregarBoF.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AgregarBoF.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AgregarBoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarBoFActionPerformed(evt);
            }
        });
        jToolBar1.add(AgregarBoF);
        jToolBar1.add(jSeparator1);

        Editar.setText("Editar");
        Editar.setFocusable(false);
        Editar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Editar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });
        jToolBar1.add(Editar);
        jToolBar1.add(jSeparator2);

        jLabel1.setText("                                                                                                                        ");
        jToolBar1.add(jLabel1);

        Buscador.setBackground(new java.awt.Color(70, 110, 196));
        Buscador.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Buscador.setForeground(new java.awt.Color(0, 0, 0));
        Buscador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Buscador.setText("Buscador");
        Buscador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Buscador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscadorMouseClicked(evt);
            }
        });
        Buscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BuscadorKeyTyped(evt);
            }
        });
        jToolBar1.add(Buscador);
        jToolBar1.add(jSeparator3);

        Eliminar.setText("Eliminar");
        Eliminar.setFocusable(false);
        Eliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Eliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(Eliminar);

        jPanel1.add(jToolBar1, java.awt.BorderLayout.PAGE_END);

        TablaBoF.setBackground(new java.awt.Color(204, 204, 204));
        TablaBoF.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        TablaBoF.setForeground(new java.awt.Color(0, 0, 0));
        TablaBoF.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaBoF.setRowHeight(27);
        TablaBoF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaBoFMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaBoF);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        Panel.addTab("Lista de Boletas/Facturas", jPanel1);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Folio:");

        Folio.setBackground(new java.awt.Color(70, 110, 196));
        Folio.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Folio.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Precio Neto:");

        Precio.setBackground(new java.awt.Color(70, 110, 196));
        Precio.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Precio.setForeground(new java.awt.Color(0, 0, 0));
        Precio.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Fecha:");

        Fecha.setBackground(new java.awt.Color(70, 110, 196));
        Fecha.setForeground(new java.awt.Color(0, 0, 0));
        try {
            Fecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Fecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Fecha.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("(AAAA/MM/DD)");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Tipo:");

        ComboMetodoP.setBackground(new java.awt.Color(70, 110, 196));
        ComboMetodoP.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ComboMetodoP.setForeground(new java.awt.Color(0, 0, 0));
        ComboMetodoP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Hora.setBackground(new java.awt.Color(70, 110, 196));
        Hora.setForeground(new java.awt.Color(0, 0, 0));
        try {
            Hora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Hora.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Hora.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Hora:");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("(HH/MM)");

        ComboTipo.setBackground(new java.awt.Color(70, 110, 196));
        ComboTipo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ComboTipo.setForeground(new java.awt.Color(0, 0, 0));
        ComboTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Metodo de Pago:");

        Guardar.setBackground(new java.awt.Color(204, 204, 204));
        Guardar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Guardar.setForeground(new java.awt.Color(0, 0, 0));
        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(127, 127, 127)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6))
                            .addGap(33, 33, 33)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Hora, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Precio, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Folio, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ComboMetodoP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGap(151, 151, 151)
                            .addComponent(ComboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(164, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(425, 425, 425))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(401, 401, 401))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Folio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ComboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboMetodoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        Panel.addTab("Gestion Boletas/Facturas", jPanel2);

        getContentPane().add(Panel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarBoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarBoFActionPerformed
        sswitch=0;
        Panel.setSelectedIndex(1);
        Folio.grabFocus();
    }//GEN-LAST:event_AgregarBoFActionPerformed

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        if (filaBoF>-1) {
            codBoF=Integer.parseInt(String.valueOf(TablaBoF.getValueAt(filaBoF, 0)));
            Folio.setText(String.valueOf(TablaBoF.getValueAt(filaBoF, 1)));
            Precio.setText(String.valueOf(TablaBoF.getValueAt(filaBoF, 2)));
            Fecha.setText(String.valueOf(TablaBoF.getValueAt(filaBoF, 9)));
            Hora.setText(String.valueOf(TablaBoF.getValueAt(filaBoF, 8)));
            sswitch=1;
            Panel.setSelectedIndex(1);
        } else {
           JOptionPane.showMessageDialog(this, "DEBE SELECCIONAR UNA FILA","ADVERTENCIA",JOptionPane.OK_OPTION+JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_EditarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        if (filaBoF>-1) {
            int respuesta=JOptionPane.showConfirmDialog(this, "¿REALMENTE DESEA ELEMINAR EL REGISTRO? NO VOLVERA A RECUPERAR EL REGISTRO...");
            if (respuesta==0) {
                crbf.EliminarBoF(Integer.parseInt(String.valueOf(TablaBoF.getValueAt(filaBoF, 0))));
                LlenarTabla("");
                JOptionPane.showMessageDialog(this, "ARRIENDO ELIMINADO", "LA BIBLIOTECA",JOptionPane.OK_OPTION+JOptionPane.INFORMATION_MESSAGE);
                filaBoF=-1;
            }
        } else {
           JOptionPane.showMessageDialog(this, "DEBE SELECCIONAR UNA FILA","ADVERTENCIA",JOptionPane.OK_OPTION+JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_EliminarActionPerformed

    private void BuscadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscadorMouseClicked
        Buscador.setText("");
    }//GEN-LAST:event_BuscadorMouseClicked

    private void BuscadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscadorKeyTyped
        LlenarTabla(Buscador.getText());
    }//GEN-LAST:event_BuscadorKeyTyped

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        MetodoPago m=(MetodoPago)ComboMetodoP.getSelectedItem();
        TipoBF t=(TipoBF)ComboTipo.getSelectedItem();
        if (Folio.getText().equals("") && Precio.getText().equals("") && Fecha.getText().equals("") && Hora.getText().equals("")){
            JOptionPane.showMessageDialog(this, "DEBE INGRESAR AL MENOS UN DATO", "La biblioteca",JOptionPane.OK_OPTION+JOptionPane.INFORMATION_MESSAGE);
        }else{
            if (sswitch==0) crbf.InsertarBoF(Folio.getText(), Integer.parseInt(Precio.getText()), Date.valueOf(Fecha.getText()), Hora.getText(), t.getCod_tipobf(), m.getCod_metod());
            else crbf.EditarBoF(codBoF, Folio.getText(), Integer.parseInt(Precio.getText()), Date.valueOf(Fecha.getText()), Hora.getText(), t.getCod_tipobf(), m.getCod_metod());  
        }   
        Folio.setText("");
        Precio.setText("");
        Fecha.setText("");
        Hora.setText("");
        LlenarTabla("");
        sswitch=0;
        Panel.setSelectedIndex(0);

        JOptionPane.showMessageDialog(this, "OPERACION REALIZADA", "EL MUSEO",JOptionPane.OK_OPTION+JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_GuardarActionPerformed

    private void TablaBoFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaBoFMouseClicked
        filaBoF=TablaBoF.rowAtPoint(evt.getPoint());
    }//GEN-LAST:event_TablaBoFMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarBoF;
    private javax.swing.JTextField Buscador;
    private javax.swing.JComboBox ComboMetodoP;
    private javax.swing.JComboBox ComboTipo;
    private javax.swing.JButton Editar;
    private javax.swing.JButton Eliminar;
    private javax.swing.JFormattedTextField Fecha;
    private javax.swing.JTextField Folio;
    private javax.swing.JButton Guardar;
    private javax.swing.JFormattedTextField Hora;
    private javax.swing.JTabbedPane Panel;
    private javax.swing.JTextField Precio;
    private javax.swing.JTable TablaBoF;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JLabel registros;
    // End of variables declaration//GEN-END:variables
}
