/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Control_AutorLibro;
import Controlador.Control_CategoriaLibro;
import Modelo.Categoria;
import Modelo.CategoriaLibro;
import Modelo.Libros;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mark-
 */
public class FRM_Categorias extends javax.swing.JInternalFrame {
    Control_CategoriaLibro crc=new Control_CategoriaLibro();
    int codCat;
    DefaultTableModel tabla=new DefaultTableModel();
    
    public void LlenarTablaCateLibro(String dato){
    tabla.setColumnCount(0);
        tabla.addColumn("ISBN de Libro");
        tabla.addColumn("Titulo de Libro");
        tabla.addColumn("Numero de Paginas");
        tabla.addColumn("Precio de Libro");
        tabla.addColumn("Categoria");
        List<CategoriaLibro> lista=crc.ListarCategLibro(dato);
        RegistrosC.setText("N° DE LIBROS CON CATEGORIAS= "+lista.size());
        tabla.setNumRows(lista.size());
        for (int i = 0; i < lista.size(); i++) {
            tabla.setValueAt(lista.get(i).getIsbn_libro(), i, 0);
            tabla.setValueAt(lista.get(i).getTitulo_libro(), i, 1);
            tabla.setValueAt(lista.get(i).getPag_libro(), i, 2);
            tabla.setValueAt(lista.get(i).getPrecio_libro(), i, 3);
            tabla.setValueAt(lista.get(i).getNom_cate(), i, 4);
        }
        TablaCategorias.setModel(tabla);
    }
    
     //COMBOBOX PARA GESTION DE CATEGORIAS EN LIBROS
    private void ComboCategoria(){
       DefaultComboBoxModel combo = new DefaultComboBoxModel();
        Control_CategoriaLibro ccal=new Control_CategoriaLibro();
        List<Categoria> lista=ccal.ComboBoxCate();
        for(Categoria C:lista){
            C = new Categoria(C.getCod_cate(), C.getNom_cate());
            combo.addElement(C);
        }
        ComboCate.setModel(combo);
    }
    
    private void ComboLibros(){
       DefaultComboBoxModel combo = new DefaultComboBoxModel();
        Control_AutorLibro ca=new Control_AutorLibro();
        List<Libros> lista=ca.ComboBoxLibros();
        for(Libros L:lista){
            L = new Libros(L.getCod_libro(), L.getTitulo_libro());
            combo.addElement(L);
        }
        ComboLibro.setModel(combo);
    }
    public FRM_Categorias() {
        initComponents();
        LlenarTablaCateLibro("");
        ComboCategoria();
        ComboLibros();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelCategorias = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jToolBar12 = new javax.swing.JToolBar();
        RegistrosC = new javax.swing.JLabel();
        jToolBar10 = new javax.swing.JToolBar();
        AgregarCategoria = new javax.swing.JButton();
        jSeparator36 = new javax.swing.JToolBar.Separator();
        jSeparator37 = new javax.swing.JToolBar.Separator();
        jLabel40 = new javax.swing.JLabel();
        jSeparator38 = new javax.swing.JToolBar.Separator();
        jSeparator41 = new javax.swing.JToolBar.Separator();
        BuscadorCategoria = new javax.swing.JTextField();
        jSeparator42 = new javax.swing.JToolBar.Separator();
        jScrollPane5 = new javax.swing.JScrollPane();
        TablaCategorias = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        ComboLibro = new javax.swing.JComboBox();
        jLabel50 = new javax.swing.JLabel();
        ComboCate = new javax.swing.JComboBox();
        GuardarCategoriaLibro = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 102, 102));
        setClosable(true);

        PanelCategorias.setBackground(new java.awt.Color(153, 153, 153));
        PanelCategorias.setForeground(new java.awt.Color(0, 0, 0));
        PanelCategorias.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        PanelCategorias.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jPanel1.setLayout(new java.awt.BorderLayout());

        jToolBar12.setBackground(new java.awt.Color(204, 204, 204));
        jToolBar12.setFloatable(false);
        jToolBar12.setForeground(new java.awt.Color(204, 204, 204));
        jToolBar12.setRollover(true);

        RegistrosC.setForeground(new java.awt.Color(0, 0, 0));
        RegistrosC.setText("jLabel5");
        jToolBar12.add(RegistrosC);

        jPanel1.add(jToolBar12, java.awt.BorderLayout.PAGE_START);

        jToolBar10.setBackground(new java.awt.Color(204, 204, 204));
        jToolBar10.setFloatable(false);
        jToolBar10.setRollover(true);

        AgregarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/matematicas.png"))); // NOI18N
        AgregarCategoria.setFocusable(false);
        AgregarCategoria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AgregarCategoria.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AgregarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarCategoriaActionPerformed(evt);
            }
        });
        jToolBar10.add(AgregarCategoria);
        jToolBar10.add(jSeparator36);
        jToolBar10.add(jSeparator37);

        jLabel40.setText("                                            ");
        jToolBar10.add(jLabel40);
        jToolBar10.add(jSeparator38);
        jToolBar10.add(jSeparator41);

        BuscadorCategoria.setBackground(new java.awt.Color(70, 110, 196));
        BuscadorCategoria.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BuscadorCategoria.setForeground(new java.awt.Color(0, 0, 0));
        BuscadorCategoria.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BuscadorCategoria.setText("Buscador");
        BuscadorCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscadorCategoriaMouseClicked(evt);
            }
        });
        BuscadorCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BuscadorCategoriaKeyTyped(evt);
            }
        });
        jToolBar10.add(BuscadorCategoria);
        jToolBar10.add(jSeparator42);

        jPanel1.add(jToolBar10, java.awt.BorderLayout.PAGE_END);

        TablaCategorias.setBackground(new java.awt.Color(204, 204, 204));
        TablaCategorias.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        TablaCategorias.setForeground(new java.awt.Color(0, 0, 0));
        TablaCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaCategorias.setRowHeight(25);
        jScrollPane5.setViewportView(TablaCategorias);

        jPanel1.add(jScrollPane5, java.awt.BorderLayout.CENTER);

        PanelCategorias.addTab("Libros en Categorias", jPanel1);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel49.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(0, 0, 0));
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("Titulo de Libro:");

        ComboLibro.setBackground(new java.awt.Color(70, 110, 196));
        ComboLibro.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ComboLibro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel50.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(0, 0, 0));
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setText("Categoria Disponible:");

        ComboCate.setBackground(new java.awt.Color(70, 110, 196));
        ComboCate.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ComboCate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        GuardarCategoriaLibro.setBackground(new java.awt.Color(204, 204, 204));
        GuardarCategoriaLibro.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        GuardarCategoriaLibro.setText("Guardar");
        GuardarCategoriaLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarCategoriaLibroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel49, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 38, Short.MAX_VALUE)
                                .addComponent(ComboCate, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ComboLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(GuardarCategoriaLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel49)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ComboLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel50)
                .addGap(18, 18, 18)
                .addComponent(ComboCate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(GuardarCategoriaLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        PanelCategorias.addTab("Gestion", jPanel2);

        getContentPane().add(PanelCategorias, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarCategoriaActionPerformed

        PanelCategorias.setSelectedIndex(1);
    }//GEN-LAST:event_AgregarCategoriaActionPerformed

    private void BuscadorCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscadorCategoriaMouseClicked
        BuscadorCategoria.setText("");
    }//GEN-LAST:event_BuscadorCategoriaMouseClicked

    private void BuscadorCategoriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscadorCategoriaKeyTyped
        LlenarTablaCateLibro(BuscadorCategoria.getText());
    }//GEN-LAST:event_BuscadorCategoriaKeyTyped

    private void GuardarCategoriaLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarCategoriaLibroActionPerformed
        Libros lib=(Libros)ComboLibro.getSelectedItem();
        Categoria cat=(Categoria)ComboCate.getSelectedItem();
        crc.InsertarCategLibro(cat.getCod_cate(), lib.getCod_libro());
        LlenarTablaCateLibro("");
        PanelCategorias.setSelectedIndex(0);
        JOptionPane.showMessageDialog(this, "OPERACION REALIZADA", "LA BIBLIOTECA",JOptionPane.OK_OPTION+JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_GuardarCategoriaLibroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarCategoria;
    private javax.swing.JTextField BuscadorCategoria;
    private javax.swing.JComboBox ComboCate;
    private javax.swing.JComboBox ComboLibro;
    private javax.swing.JButton GuardarCategoriaLibro;
    private javax.swing.JTabbedPane PanelCategorias;
    private javax.swing.JLabel RegistrosC;
    private javax.swing.JTable TablaCategorias;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JToolBar.Separator jSeparator36;
    private javax.swing.JToolBar.Separator jSeparator37;
    private javax.swing.JToolBar.Separator jSeparator38;
    private javax.swing.JToolBar.Separator jSeparator41;
    private javax.swing.JToolBar.Separator jSeparator42;
    private javax.swing.JToolBar jToolBar10;
    private javax.swing.JToolBar jToolBar12;
    // End of variables declaration//GEN-END:variables
}
