/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Control_Libros;
import Modelo.Editorial;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mark-
 */
public class FRM_Editorial extends javax.swing.JInternalFrame {
    Control_Libros crl=new Control_Libros();
    private int filaE=-1;
    private int sswitch=0;
    int codE;
    DefaultTableModel tabla=new DefaultTableModel();
    
    //tabla de editoriales
    public void LlenarTablaEditoriales(String Dato){
    tabla.setColumnCount(0);
        tabla.addColumn("Codigo");
        tabla.addColumn("Nombre de Editorial");
        List<Editorial> lista=crl.listaEdit(Dato);
        tabla.setNumRows(lista.size());
        RegistrosEdit.setText("N° EDITORIALES DISPONIBLES= "+lista.size());
        for (int i = 0; i < lista.size(); i++) {
            tabla.setValueAt(lista.get(i).getCod_edit(), i, 0);
            tabla.setValueAt(lista.get(i).getNom_edit(), i, 1);
        }
        TablaEditoriales.setModel(tabla);
        TablaEditoriales.getColumnModel().getColumn(0).setMaxWidth(0);
        TablaEditoriales.getColumnModel().getColumn(0).setMinWidth(0);
        TablaEditoriales.getColumnModel().getColumn(0).setPreferredWidth(0);
    } 
    
    /**
     * Creates new form FRM_Editorial
     */
    public FRM_Editorial() {
        initComponents();
        LlenarTablaEditoriales("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelEditoriales = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jToolBar12 = new javax.swing.JToolBar();
        RegistrosEdit = new javax.swing.JLabel();
        jToolBar10 = new javax.swing.JToolBar();
        AgregarE = new javax.swing.JButton();
        jSeparator36 = new javax.swing.JToolBar.Separator();
        EditarE = new javax.swing.JButton();
        jSeparator37 = new javax.swing.JToolBar.Separator();
        jLabel40 = new javax.swing.JLabel();
        jSeparator38 = new javax.swing.JToolBar.Separator();
        jSeparator41 = new javax.swing.JToolBar.Separator();
        BuscadorEdit = new javax.swing.JTextField();
        jSeparator42 = new javax.swing.JToolBar.Separator();
        EliminarE = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        TablaEditoriales = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        Nom = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        GuardarEditorial = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 102, 102));
        setClosable(true);

        PanelEditoriales.setBackground(new java.awt.Color(153, 153, 153));
        PanelEditoriales.setForeground(new java.awt.Color(0, 0, 0));
        PanelEditoriales.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        PanelEditoriales.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jPanel1.setLayout(new java.awt.BorderLayout());

        jToolBar12.setBackground(new java.awt.Color(204, 204, 204));
        jToolBar12.setFloatable(false);
        jToolBar12.setForeground(new java.awt.Color(204, 204, 204));
        jToolBar12.setRollover(true);

        RegistrosEdit.setForeground(new java.awt.Color(0, 0, 0));
        RegistrosEdit.setText("jLabel5");
        jToolBar12.add(RegistrosEdit);

        jPanel1.add(jToolBar12, java.awt.BorderLayout.PAGE_START);

        jToolBar10.setBackground(new java.awt.Color(204, 204, 204));
        jToolBar10.setFloatable(false);
        jToolBar10.setRollover(true);

        AgregarE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mas.png"))); // NOI18N
        AgregarE.setFocusable(false);
        AgregarE.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AgregarE.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AgregarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarEActionPerformed(evt);
            }
        });
        jToolBar10.add(AgregarE);
        jToolBar10.add(jSeparator36);

        EditarE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lapiz.png"))); // NOI18N
        EditarE.setFocusable(false);
        EditarE.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EditarE.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        EditarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarEActionPerformed(evt);
            }
        });
        jToolBar10.add(EditarE);
        jToolBar10.add(jSeparator37);

        jLabel40.setText("                    ");
        jToolBar10.add(jLabel40);
        jToolBar10.add(jSeparator38);
        jToolBar10.add(jSeparator41);

        BuscadorEdit.setBackground(new java.awt.Color(70, 110, 196));
        BuscadorEdit.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BuscadorEdit.setForeground(new java.awt.Color(0, 0, 0));
        BuscadorEdit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BuscadorEdit.setText("Buscador");
        BuscadorEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscadorEditMouseClicked(evt);
            }
        });
        BuscadorEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BuscadorEditKeyTyped(evt);
            }
        });
        jToolBar10.add(BuscadorEdit);
        jToolBar10.add(jSeparator42);

        EliminarE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/basura.png"))); // NOI18N
        EliminarE.setFocusable(false);
        EliminarE.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EliminarE.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        EliminarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarEActionPerformed(evt);
            }
        });
        jToolBar10.add(EliminarE);

        jPanel1.add(jToolBar10, java.awt.BorderLayout.PAGE_END);

        TablaEditoriales.setBackground(new java.awt.Color(204, 204, 204));
        TablaEditoriales.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        TablaEditoriales.setForeground(new java.awt.Color(0, 0, 0));
        TablaEditoriales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaEditoriales.setRowHeight(25);
        TablaEditoriales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaEditorialesMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(TablaEditoriales);

        jPanel1.add(jScrollPane5, java.awt.BorderLayout.CENTER);

        PanelEditoriales.addTab("Lista de Editoriales", jPanel1);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        Nom.setBackground(new java.awt.Color(70, 110, 196));
        Nom.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Nom.setForeground(new java.awt.Color(0, 0, 0));
        Nom.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel49.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(0, 0, 0));
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("Nombre Editorial:");

        GuardarEditorial.setBackground(new java.awt.Color(204, 204, 204));
        GuardarEditorial.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        GuardarEditorial.setText("Guardar");
        GuardarEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarEditorialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel49, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(Nom, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(GuardarEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(175, 175, 175))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel49)
                .addGap(31, 31, 31)
                .addComponent(Nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(GuardarEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        PanelEditoriales.addTab("Gestion", jPanel2);

        getContentPane().add(PanelEditoriales, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarEActionPerformed
        sswitch=0;
        PanelEditoriales.setSelectedIndex(1);
        Nom.grabFocus();
    }//GEN-LAST:event_AgregarEActionPerformed

    private void EditarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarEActionPerformed
        if (filaE>-1) {
            codE=Integer.parseInt(String.valueOf(TablaEditoriales.getValueAt(filaE, 0)));
            Nom.setText(String.valueOf(TablaEditoriales.getValueAt(filaE, 1)));
            sswitch=1;
            PanelEditoriales.setSelectedIndex(1);
        } else {
            JOptionPane.showMessageDialog(this, "DEBE SELECCIONAR UNA FILA","ADVERTENCIA",JOptionPane.OK_OPTION+JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_EditarEActionPerformed

    private void BuscadorEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscadorEditMouseClicked
        BuscadorEdit.setText("");
    }//GEN-LAST:event_BuscadorEditMouseClicked

    private void BuscadorEditKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscadorEditKeyTyped
        LlenarTablaEditoriales(BuscadorEdit.getText());
    }//GEN-LAST:event_BuscadorEditKeyTyped

    private void EliminarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarEActionPerformed
        if (filaE>-1) {
            int respuesta=JOptionPane.showConfirmDialog(this, "¿REALMENTE DESEA ELEMINAR EL REGISTRO? NO VOLVERA A RECUPERAR EL REGISTRO..."+" "
                +String.valueOf(TablaEditoriales.getValueAt(filaE, 1)),"ADVERTENCIA",JOptionPane.YES_NO_OPTION+JOptionPane.WARNING_MESSAGE);
            if (respuesta==0) {
                crl.eliminarEditoriales(Integer.parseInt(String.valueOf(TablaEditoriales.getValueAt(filaE, 0))));
                LlenarTablaEditoriales("");
                JOptionPane.showMessageDialog(this, "LIBRO ELIMINADO", "LA BIBLIOTECA",JOptionPane.OK_OPTION+JOptionPane.INFORMATION_MESSAGE);
                filaE=-1;
            }
        } else {
            JOptionPane.showMessageDialog(this, "DEBE SELECCIONAR UNA FILA","ADVERTENCIA",JOptionPane.OK_OPTION+JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_EliminarEActionPerformed

    private void TablaEditorialesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaEditorialesMouseClicked
        filaE=TablaEditoriales.rowAtPoint(evt.getPoint());
    }//GEN-LAST:event_TablaEditorialesMouseClicked

    private void GuardarEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarEditorialActionPerformed
        if (Nom.getText().equals("") ){
            JOptionPane.showMessageDialog(this, "DEBE INGRESAR EL DATO", "La biblioteca",JOptionPane.OK_OPTION+JOptionPane.INFORMATION_MESSAGE);
            Nom.grabFocus();
        }else{
            if (sswitch==0) crl.InsertarEdit(Nom.getText());

            else crl.EditarEditoriales(codE, Nom.getText());

            
        }
        Nom.setText("");
        LlenarTablaEditoriales("");
        sswitch=0;
        PanelEditoriales.setSelectedIndex(0);
        JOptionPane.showMessageDialog(this, "OPERACION REALIZADA", "LA BIBLIOTECA",JOptionPane.OK_OPTION+JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_GuardarEditorialActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarE;
    private javax.swing.JTextField BuscadorEdit;
    private javax.swing.JButton EditarE;
    private javax.swing.JButton EliminarE;
    private javax.swing.JButton GuardarEditorial;
    private javax.swing.JTextField Nom;
    private javax.swing.JTabbedPane PanelEditoriales;
    private javax.swing.JLabel RegistrosEdit;
    private javax.swing.JTable TablaEditoriales;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JToolBar.Separator jSeparator36;
    private javax.swing.JToolBar.Separator jSeparator37;
    private javax.swing.JToolBar.Separator jSeparator38;
    private javax.swing.JToolBar.Separator jSeparator41;
    private javax.swing.JToolBar.Separator jSeparator42;
    private javax.swing.JToolBar jToolBar10;
    private javax.swing.JToolBar jToolBar12;
    // End of variables declaration//GEN-END:variables
}
