/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Control_Autores;
import Modelo.NacionAutor;
import Modelo.PaisAutor;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mark-
 */
public class FRM_Nacionalidad extends javax.swing.JInternalFrame {
    Control_Autores cra=new Control_Autores();
    private int filaN=-1;
    private int sswitch;
    int codN;
    DefaultTableModel tabla=new DefaultTableModel();
    
    public void LlenarTablaNac(String dato){
    tabla.setColumnCount(0);
        tabla.addColumn("Codigo");
        tabla.addColumn("Descripcion Nacionalidad");
        tabla.addColumn("Pais Asociado");
        List<NacionAutor> lista=cra.listaNacionalidad(dato);
        RegistrosEdit.setText("N° DE NACIONALDADES GUARDADAS= "+lista.size());
        tabla.setNumRows(lista.size());
        for (int i = 0; i < lista.size(); i++) {
            tabla.setValueAt(lista.get(i).getCod_nac(), i, 0);
            tabla.setValueAt(lista.get(i).getNom_nac(), i, 1);
            tabla.setValueAt(lista.get(i).getNom_pais(), i, 2);
        }
        TablaNacionalidad.setModel(tabla);
        TablaNacionalidad.getColumnModel().getColumn(0).setMaxWidth(0);
        TablaNacionalidad.getColumnModel().getColumn(0).setMinWidth(0);
        TablaNacionalidad.getColumnModel().getColumn(0).setPreferredWidth(0);
    }
    
    
    private void ComboPaises(){
       DefaultComboBoxModel combo = new DefaultComboBoxModel();
        Control_Autores ca=new Control_Autores();
        List<PaisAutor> lista=ca.comboPais();
        for(PaisAutor P:lista){
            P = new PaisAutor(P.getCod_pais(), P.getNom_pais());
            combo.addElement(P);
        }
        ComboPais.setModel(combo);
    }
    
    public FRM_Nacionalidad() {
        initComponents();
        LlenarTablaNac("");
        ComboPaises();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelNac = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jToolBar12 = new javax.swing.JToolBar();
        RegistrosEdit = new javax.swing.JLabel();
        jToolBar10 = new javax.swing.JToolBar();
        AgregarN = new javax.swing.JButton();
        jSeparator36 = new javax.swing.JToolBar.Separator();
        jSeparator37 = new javax.swing.JToolBar.Separator();
        jLabel40 = new javax.swing.JLabel();
        jSeparator38 = new javax.swing.JToolBar.Separator();
        jSeparator41 = new javax.swing.JToolBar.Separator();
        BuscadorEdit = new javax.swing.JTextField();
        jSeparator42 = new javax.swing.JToolBar.Separator();
        EliminarN = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        TablaNacionalidad = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel59 = new javax.swing.JLabel();
        DescNac = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        ComboPais = new javax.swing.JComboBox();
        GuardarNacion1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 102, 102));
        setClosable(true);

        PanelNac.setBackground(new java.awt.Color(153, 153, 153));
        PanelNac.setForeground(new java.awt.Color(0, 0, 0));
        PanelNac.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        PanelNac.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jPanel1.setLayout(new java.awt.BorderLayout());

        jToolBar12.setBackground(new java.awt.Color(204, 204, 204));
        jToolBar12.setFloatable(false);
        jToolBar12.setForeground(new java.awt.Color(204, 204, 204));
        jToolBar12.setRollover(true);

        RegistrosEdit.setForeground(new java.awt.Color(0, 0, 0));
        RegistrosEdit.setText("jLabel5");
        jToolBar12.add(RegistrosEdit);

        jPanel1.add(jToolBar12, java.awt.BorderLayout.PAGE_START);

        jToolBar10.setBackground(new java.awt.Color(204, 204, 204));
        jToolBar10.setFloatable(false);
        jToolBar10.setRollover(true);

        AgregarN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bandera.png"))); // NOI18N
        AgregarN.setFocusable(false);
        AgregarN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AgregarN.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AgregarN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarNActionPerformed(evt);
            }
        });
        jToolBar10.add(AgregarN);
        jToolBar10.add(jSeparator36);
        jToolBar10.add(jSeparator37);

        jLabel40.setText("                    ");
        jToolBar10.add(jLabel40);
        jToolBar10.add(jSeparator38);
        jToolBar10.add(jSeparator41);

        BuscadorEdit.setBackground(new java.awt.Color(70, 110, 196));
        BuscadorEdit.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BuscadorEdit.setForeground(new java.awt.Color(0, 0, 0));
        BuscadorEdit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BuscadorEdit.setText("Buscador");
        BuscadorEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscadorEditMouseClicked(evt);
            }
        });
        BuscadorEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BuscadorEditKeyTyped(evt);
            }
        });
        jToolBar10.add(BuscadorEdit);
        jToolBar10.add(jSeparator42);

        EliminarN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/basura.png"))); // NOI18N
        EliminarN.setFocusable(false);
        EliminarN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EliminarN.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        EliminarN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarNActionPerformed(evt);
            }
        });
        jToolBar10.add(EliminarN);

        jPanel1.add(jToolBar10, java.awt.BorderLayout.PAGE_END);

        TablaNacionalidad.setBackground(new java.awt.Color(204, 204, 204));
        TablaNacionalidad.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        TablaNacionalidad.setForeground(new java.awt.Color(0, 0, 0));
        TablaNacionalidad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaNacionalidad.setRowHeight(25);
        TablaNacionalidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaNacionalidadMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(TablaNacionalidad);

        jPanel1.add(jScrollPane9, java.awt.BorderLayout.CENTER);

        PanelNac.addTab("Lista de Nacionalidades", jPanel1);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel42.setBackground(new java.awt.Color(0, 0, 0));
        jLabel42.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 0, 0));
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("Gestión de Nacionalidades");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel59.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel59.setText("Descripcion de Nacion:");

        DescNac.setBackground(new java.awt.Color(70, 110, 196));
        DescNac.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        DescNac.setForeground(new java.awt.Color(0, 0, 0));
        DescNac.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel62.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel62.setText("Pais:");

        ComboPais.setBackground(new java.awt.Color(70, 110, 196));
        ComboPais.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ComboPais.setForeground(new java.awt.Color(0, 0, 0));
        ComboPais.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        GuardarNacion1.setBackground(new java.awt.Color(204, 204, 204));
        GuardarNacion1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        GuardarNacion1.setText("Guardar");
        GuardarNacion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarNacion1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(190, 190, 190)
                                .addComponent(jLabel59))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(257, 257, 257)
                                .addComponent(jLabel62)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ComboPais, 0, 396, Short.MAX_VALUE)
                    .addComponent(DescNac))
                .addGap(74, 74, 74))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(GuardarNacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel59)
                .addGap(18, 18, 18)
                .addComponent(DescNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel62)
                .addGap(18, 18, 18)
                .addComponent(ComboPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(GuardarNacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        PanelNac.addTab("Gestión", jPanel2);

        getContentPane().add(PanelNac, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarNActionPerformed
        sswitch=0;
        PanelNac.setSelectedIndex(1);
        DescNac.grabFocus();
    }//GEN-LAST:event_AgregarNActionPerformed

    private void BuscadorEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscadorEditMouseClicked
        BuscadorEdit.setText("");
    }//GEN-LAST:event_BuscadorEditMouseClicked

    private void BuscadorEditKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscadorEditKeyTyped
        LlenarTablaNac(BuscadorEdit.getText());
    }//GEN-LAST:event_BuscadorEditKeyTyped

    private void EliminarNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarNActionPerformed
        if (filaN>-1) {
            int respuesta=JOptionPane.showConfirmDialog(this, "¿REALMENTE DESEA ELEMINAR EL REGISTRO? NO VOLVERA A RECUPERAR EL REGISTRO..."+" "
                +String.valueOf(TablaNacionalidad.getValueAt(filaN, 1)),"ADVERTENCIA",JOptionPane.YES_NO_OPTION+JOptionPane.WARNING_MESSAGE);
            if (respuesta==0) {
                cra.EliminarNacion(Integer.parseInt(String.valueOf(TablaNacionalidad.getValueAt(filaN, 0))));
                LlenarTablaNac("");
                JOptionPane.showMessageDialog(this, "NACIONALIDAD ELIMINADA", "LA BIBLIOTECA",JOptionPane.OK_OPTION+JOptionPane.INFORMATION_MESSAGE);
                filaN=-1;
            }
        } else {
            JOptionPane.showMessageDialog(this, "DEBE SELECCIONAR UNA FILA","ADVERTENCIA",JOptionPane.OK_OPTION+JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_EliminarNActionPerformed

    private void GuardarNacion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarNacion1ActionPerformed
        PaisAutor pa=(PaisAutor)ComboPais.getSelectedItem();
        if (DescNac.getText().equals("") ){
            JOptionPane.showMessageDialog(this, "DEBE INGRESAR EL DATO", "La biblioteca",JOptionPane.OK_OPTION+JOptionPane.INFORMATION_MESSAGE);
            DescNac.grabFocus();
        }else{
        if (sswitch==0) cra.IngresarNacion(DescNac.getText(), pa.getCod_pais());
        
        }
        PanelNac.setSelectedIndex(0);
        DescNac.setText("");
        LlenarTablaNac("");
        JOptionPane.showMessageDialog(this, "OPERACION REALIZADA", "LA BIBLIOTECA",JOptionPane.OK_OPTION+JOptionPane.INFORMATION_MESSAGE);
        sswitch=0;
    }//GEN-LAST:event_GuardarNacion1ActionPerformed

    private void TablaNacionalidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaNacionalidadMouseClicked
        filaN=TablaNacionalidad.rowAtPoint(evt.getPoint());
    }//GEN-LAST:event_TablaNacionalidadMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarN;
    private javax.swing.JTextField BuscadorEdit;
    private javax.swing.JComboBox ComboPais;
    private javax.swing.JTextField DescNac;
    private javax.swing.JButton EliminarN;
    private javax.swing.JButton GuardarNacion1;
    private javax.swing.JTabbedPane PanelNac;
    private javax.swing.JLabel RegistrosEdit;
    private javax.swing.JTable TablaNacionalidad;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator36;
    private javax.swing.JToolBar.Separator jSeparator37;
    private javax.swing.JToolBar.Separator jSeparator38;
    private javax.swing.JToolBar.Separator jSeparator41;
    private javax.swing.JToolBar.Separator jSeparator42;
    private javax.swing.JToolBar jToolBar10;
    private javax.swing.JToolBar jToolBar12;
    // End of variables declaration//GEN-END:variables
}
