/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Control_Seguridad;
import Controlador.Control_Usuario;
import Modelo.Cargo;
import Modelo.Usuarios;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mark-
 */
public class FRM_Usuarios extends javax.swing.JInternalFrame {
    Control_Seguridad cs=new Control_Seguridad();
    Control_Usuario cru=new Control_Usuario();
    private int filau=-1;
    int codu;
    private int sswitch=0;
    DefaultTableModel tabla=new DefaultTableModel();
    
    public void LlenarTablaUsuario(String dato){
    tabla.setColumnCount(0);
        tabla.addColumn("Codigo");
        tabla.addColumn("Usuario");
        tabla.addColumn("Contraseña");
        tabla.addColumn("Rol");
        List<Usuarios> lista=cru.listar(dato);
        tabla.setNumRows(lista.size());
        cantUsuarios.setText("CANTIDAD DE REGISTROS= "+lista.size());
        for (int i = 0; i < lista.size(); i++) {
            tabla.setValueAt(lista.get(i).getCod_usu(), i, 0);
            tabla.setValueAt(lista.get(i).getNom_usu(), i, 1);
            tabla.setValueAt(lista.get(i).getPass_usu(), i, 2);
            tabla.setValueAt(lista.get(i).getNom_cargo(), i, 3);
        }
        TablaUsuarios.setModel(tabla);
        TablaUsuarios.getColumnModel().getColumn(0).setMaxWidth(0);
        TablaUsuarios.getColumnModel().getColumn(0).setMinWidth(0);
        TablaUsuarios.getColumnModel().getColumn(0).setPreferredWidth(0);
        
        TablaUsuarios.getColumnModel().getColumn(2).setMaxWidth(0);
        TablaUsuarios.getColumnModel().getColumn(2).setMinWidth(0);
        TablaUsuarios.getColumnModel().getColumn(2).setPreferredWidth(0);
    }
    
    private void ComboRol(){
       DefaultComboBoxModel combo = new DefaultComboBoxModel();
        Control_Usuario cu=new Control_Usuario();
        List<Cargo> lista=cu.ComboBoxCargosU();
        for(Cargo c:lista){
            c = new Cargo(c.getCod_cargo(), c.getNom_cargo());
            combo.addElement(c);
        }
        ComboRol.setModel(combo);
    }
    
    public FRM_Usuarios() {
        initComponents();
        LlenarTablaUsuario("");
        ComboRol();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Panel = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        cantUsuarios = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        AgregarUsuarios = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        EditarUsuarios = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jLabel1 = new javax.swing.JLabel();
        BuscadorUsuarios = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        EliminarUsuarios = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaUsuarios = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Usuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ComboRol = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        GuardarUsuario = new javax.swing.JButton();
        Password = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(102, 102, 102));
        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new java.awt.BorderLayout());

        Panel.setBackground(new java.awt.Color(153, 153, 153));
        Panel.setForeground(new java.awt.Color(0, 0, 0));
        Panel.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jToolBar2.setBackground(new java.awt.Color(204, 204, 204));
        jToolBar2.setBorder(null);
        jToolBar2.setFloatable(false);
        jToolBar2.setForeground(new java.awt.Color(102, 102, 102));
        jToolBar2.setRollover(true);

        cantUsuarios.setBackground(new java.awt.Color(0, 0, 0));
        cantUsuarios.setForeground(new java.awt.Color(0, 0, 0));
        cantUsuarios.setText("jLabel1");
        jToolBar2.add(cantUsuarios);

        jPanel2.add(jToolBar2, java.awt.BorderLayout.PAGE_START);

        jToolBar1.setBackground(new java.awt.Color(204, 204, 204));
        jToolBar1.setBorder(null);
        jToolBar1.setFloatable(false);
        jToolBar1.setForeground(new java.awt.Color(204, 204, 204));
        jToolBar1.setRollover(true);

        AgregarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mas usuarios.png"))); // NOI18N
        AgregarUsuarios.setFocusable(false);
        AgregarUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AgregarUsuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AgregarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarUsuariosActionPerformed(evt);
            }
        });
        jToolBar1.add(AgregarUsuarios);
        jToolBar1.add(jSeparator1);

        EditarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lapiz.png"))); // NOI18N
        EditarUsuarios.setFocusable(false);
        EditarUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EditarUsuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        EditarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarUsuariosActionPerformed(evt);
            }
        });
        jToolBar1.add(EditarUsuarios);
        jToolBar1.add(jSeparator2);

        jLabel1.setText("                                              ");
        jToolBar1.add(jLabel1);

        BuscadorUsuarios.setBackground(new java.awt.Color(70, 110, 196));
        BuscadorUsuarios.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BuscadorUsuarios.setForeground(new java.awt.Color(0, 0, 0));
        BuscadorUsuarios.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BuscadorUsuarios.setText("Buscador");
        BuscadorUsuarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BuscadorUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscadorUsuariosMouseClicked(evt);
            }
        });
        BuscadorUsuarios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BuscadorUsuariosKeyTyped(evt);
            }
        });
        jToolBar1.add(BuscadorUsuarios);
        jToolBar1.add(jSeparator3);

        EliminarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/basura.png"))); // NOI18N
        EliminarUsuarios.setFocusable(false);
        EliminarUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EliminarUsuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        EliminarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarUsuariosActionPerformed(evt);
            }
        });
        jToolBar1.add(EliminarUsuarios);

        jPanel2.add(jToolBar1, java.awt.BorderLayout.PAGE_END);

        TablaUsuarios.setBackground(new java.awt.Color(204, 204, 204));
        TablaUsuarios.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        TablaUsuarios.setForeground(new java.awt.Color(0, 0, 0));
        TablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaUsuarios.setRowHeight(27);
        TablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaUsuarios);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        Panel.addTab("Lista de Usuarios", jPanel2);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Usuario:");

        Usuario.setBackground(new java.awt.Color(70, 110, 196));
        Usuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Usuario.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Contraseña:");

        ComboRol.setBackground(new java.awt.Color(70, 110, 196));
        ComboRol.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ComboRol.setForeground(new java.awt.Color(0, 0, 0));
        ComboRol.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Rol:");

        GuardarUsuario.setBackground(new java.awt.Color(204, 204, 204));
        GuardarUsuario.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        GuardarUsuario.setForeground(new java.awt.Color(0, 0, 0));
        GuardarUsuario.setText("Guardar");
        GuardarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarUsuarioActionPerformed(evt);
            }
        });

        Password.setBackground(new java.awt.Color(70, 110, 196));
        Password.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Password.setForeground(new java.awt.Color(0, 0, 0));
        Password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Password.setText("jPasswordField1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GuardarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Usuario)
                            .addComponent(ComboRol, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Password, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE))))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(GuardarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        Panel.addTab("Gestión de Usuarios", jPanel3);

        jPanel1.add(Panel, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarUsuariosActionPerformed
        sswitch=0;
        Panel.setSelectedIndex(1);
        Usuario.grabFocus();
    }//GEN-LAST:event_AgregarUsuariosActionPerformed

    private void EditarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarUsuariosActionPerformed
        if (filau>-1) {
            codu=Integer.parseInt(String.valueOf(TablaUsuarios.getValueAt(filau, 0)));
            Usuario.setText(String.valueOf(TablaUsuarios.getValueAt(filau, 1)));
            sswitch=1;
            Panel.setSelectedIndex(1);
        } else {
            JOptionPane.showMessageDialog(this, "DEBE SELECCIONAR UNA FILA","ADVERTENCIA",JOptionPane.OK_OPTION+JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_EditarUsuariosActionPerformed

    private void BuscadorUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscadorUsuariosMouseClicked
        BuscadorUsuarios.setText("");
    }//GEN-LAST:event_BuscadorUsuariosMouseClicked

    private void BuscadorUsuariosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscadorUsuariosKeyTyped
        LlenarTablaUsuario(BuscadorUsuarios.getText());
    }//GEN-LAST:event_BuscadorUsuariosKeyTyped

    private void EliminarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarUsuariosActionPerformed
        if (filau>-1) {
            int respuesta=JOptionPane.showConfirmDialog(this, "¿REALMENTE DESEA ELEMINAR EL REGISTRO? NO VOLVERA A RECUPERAR EL REGISTRO...");
            if (respuesta==0) {
                cru.EliminarUsuarios(Integer.parseInt(String.valueOf(TablaUsuarios.getValueAt(filau, 0))));
                LlenarTablaUsuario("");
                JOptionPane.showMessageDialog(this, "ARRIENDO ELIMINADO", "LA BIBLIOTECA",JOptionPane.OK_OPTION+JOptionPane.INFORMATION_MESSAGE);
                filau=-1;
            }
        } else {
            JOptionPane.showMessageDialog(this, "DEBE SELECCIONAR UNA FILA","ADVERTENCIA",JOptionPane.OK_OPTION+JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_EliminarUsuariosActionPerformed

    private void TablaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaUsuariosMouseClicked
        filau=TablaUsuarios.rowAtPoint(evt.getPoint());
    }//GEN-LAST:event_TablaUsuariosMouseClicked

    private void GuardarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarUsuarioActionPerformed
        Cargo c=(Cargo)ComboRol.getSelectedItem();
        String pass=String.copyValueOf(Password.getPassword());
        if (Usuario.getText().equals("") && pass.equals("")){
            JOptionPane.showMessageDialog(this, "DEBE INGRESAR TODOS LOS DATOS", "La biblioteca",JOptionPane.OK_OPTION+JOptionPane.INFORMATION_MESSAGE);
        }else{
            if (sswitch==0) cru.InsertarUsuarios(Usuario.getText(),  pass, c.getCod_cargo());
            else cru.EditarUsuarios(codu, Usuario.getText(),  pass, c.getCod_cargo());
        }
        Usuario.setText("");
        Password.setText("");
        LlenarTablaUsuario("");
        sswitch=0;
        Panel.setSelectedIndex(0);
        JOptionPane.showMessageDialog(this, "OPERACION REALIZADA", "EL MUSEO",JOptionPane.OK_OPTION+JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_GuardarUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarUsuarios;
    private javax.swing.JTextField BuscadorUsuarios;
    private javax.swing.JComboBox ComboRol;
    private javax.swing.JButton EditarUsuarios;
    public javax.swing.JButton EliminarUsuarios;
    private javax.swing.JButton GuardarUsuario;
    private javax.swing.JTabbedPane Panel;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTable TablaUsuarios;
    private javax.swing.JTextField Usuario;
    private javax.swing.JLabel cantUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    // End of variables declaration//GEN-END:variables
}
