/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Control_Distribuidor;
import Modelo.Comuna;
import Modelo.Distribuidor;
import Modelo.PaisDist;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mark-
 */
public class FRM_Distribuidores extends javax.swing.JInternalFrame {
    Control_Distribuidor  crd=new Control_Distribuidor();
    int codDist;
    private int filaDist=-1;
    private int sswitch=0;
    DefaultTableModel tabla=new DefaultTableModel();
    
    public void LlenarTabla1Dist(String dato){
    tabla.setColumnCount(0);
        tabla.addColumn("Codigo");
        tabla.addColumn("Rut");
        tabla.addColumn("Nombre");
        tabla.addColumn("Direccion");
        tabla.addColumn("Telefono");
        tabla.addColumn("Tiempo de Servicio");
        tabla.addColumn("Email");
        tabla.addColumn("Contacto Encargado");
        tabla.addColumn("Pais de Origen");
        tabla.addColumn("Comuna");
        List<Distribuidor> lista=crd.ListarDistribuidores(dato);
        tabla.setNumRows(lista.size());
        registros.setText("CANTIDAD DE REGISTROS= "+lista.size());
        for (int i = 0; i < lista.size(); i++) {
            tabla.setValueAt(lista.get(i).getCod_dist(), i, 0);
            tabla.setValueAt(lista.get(i).getRut_dist(), i, 1);
            tabla.setValueAt(lista.get(i).getNom_dist(), i, 2);
            tabla.setValueAt(lista.get(i).getDir_dist(), i, 3);
            tabla.setValueAt(lista.get(i).getTel_dist(), i, 4);
            tabla.setValueAt(lista.get(i).getTiempo_dist(), i, 5);
            tabla.setValueAt(lista.get(i).getEm_dist(), i, 6);
            tabla.setValueAt(lista.get(i).getContacto_dist(), i, 7);
            tabla.setValueAt(lista.get(i).getNom_pais(), i, 8);
            tabla.setValueAt(lista.get(i).getNom_comuna(), i, 9);
        }
        TablaDist.setModel(tabla);
        TablaDist.getColumnModel().getColumn(0).setMaxWidth(0);
        TablaDist.getColumnModel().getColumn(0).setMinWidth(0);
        TablaDist.getColumnModel().getColumn(0).setPreferredWidth(0);
    }
    
     private void ComboPais(){
       DefaultComboBoxModel combo = new DefaultComboBoxModel();
        Control_Distribuidor cod=new Control_Distribuidor();
        List<PaisDist> lista=cod.comboBoxPais();
        for(PaisDist P:lista){
            P = new PaisDist(P.getCod_pais(), P.getNom_pais());
            combo.addElement(P);
        }
        CPais.setModel(combo);
    }
    
    private void ComboComuna(){
       DefaultComboBoxModel combo = new DefaultComboBoxModel();
        Control_Distribuidor cod=new Control_Distribuidor();
        List<Comuna> lista=cod.comboBoxComunas();
        for(Comuna C:lista){
            C = new Comuna(C.getCod_comuna(), C.getNom_comuna());
            combo.addElement(C);
        }
        CComuna.setModel(combo);
    }
    
    public FRM_Distribuidores() {
        initComponents();
        LlenarTabla1Dist("");
        ComboPais();
        ComboComuna();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        PanelDist = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        registros = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        AgregarBoF = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        Editar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        Buscador = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        Eliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDist = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        RutDist = new javax.swing.JTextField();
        CComuna = new javax.swing.JComboBox();
        CPais = new javax.swing.JComboBox();
        GuardarDist = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        NombreDist = new javax.swing.JTextField();
        DirecDist = new javax.swing.JTextField();
        TelefonoDist = new javax.swing.JTextField();
        ServDist = new javax.swing.JTextField();
        EmailDist = new javax.swing.JTextField();
        ContacDist = new javax.swing.JTextField();

        setBackground(new java.awt.Color(153, 153, 153));
        setClosable(true);

        PanelDist.setBackground(new java.awt.Color(153, 153, 153));
        PanelDist.setForeground(new java.awt.Color(0, 0, 0));
        PanelDist.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jToolBar2.setBackground(new java.awt.Color(204, 204, 204));
        jToolBar2.setBorder(null);
        jToolBar2.setFloatable(false);
        jToolBar2.setForeground(new java.awt.Color(102, 102, 102));
        jToolBar2.setRollover(true);

        registros.setBackground(new java.awt.Color(0, 0, 0));
        registros.setForeground(new java.awt.Color(0, 0, 0));
        registros.setText("jLabel1");
        jToolBar2.add(registros);

        jPanel1.add(jToolBar2, java.awt.BorderLayout.PAGE_START);

        jToolBar1.setBackground(new java.awt.Color(204, 204, 204));
        jToolBar1.setBorder(null);
        jToolBar1.setFloatable(false);
        jToolBar1.setForeground(new java.awt.Color(204, 204, 204));
        jToolBar1.setRollover(true);

        AgregarBoF.setText("Agregar");
        AgregarBoF.setFocusable(false);
        AgregarBoF.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AgregarBoF.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AgregarBoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarBoFActionPerformed(evt);
            }
        });
        jToolBar1.add(AgregarBoF);
        jToolBar1.add(jSeparator1);

        Editar.setText("Editar");
        Editar.setFocusable(false);
        Editar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Editar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });
        jToolBar1.add(Editar);
        jToolBar1.add(jSeparator2);

        Buscador.setBackground(new java.awt.Color(70, 110, 196));
        Buscador.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Buscador.setForeground(new java.awt.Color(0, 0, 0));
        Buscador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Buscador.setText("Buscador");
        Buscador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Buscador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscadorMouseClicked(evt);
            }
        });
        Buscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BuscadorKeyTyped(evt);
            }
        });
        jToolBar1.add(Buscador);
        jToolBar1.add(jSeparator3);

        Eliminar.setText("Eliminar");
        Eliminar.setFocusable(false);
        Eliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Eliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(Eliminar);

        jPanel1.add(jToolBar1, java.awt.BorderLayout.PAGE_END);

        TablaDist.setBackground(new java.awt.Color(204, 204, 204));
        TablaDist.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        TablaDist.setForeground(new java.awt.Color(0, 0, 0));
        TablaDist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaDist.setRowHeight(27);
        TablaDist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaDistMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaDist);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        PanelDist.addTab("Distribuidores", jPanel1);

        jPanel9.setBackground(new java.awt.Color(153, 153, 153));

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Años de Serv. :");

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Email:");

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Comuna:");

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Pais de Origen:");

        RutDist.setBackground(new java.awt.Color(70, 110, 196));
        RutDist.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        RutDist.setForeground(new java.awt.Color(0, 0, 0));
        RutDist.setCaretColor(new java.awt.Color(0, 0, 0));

        CComuna.setBackground(new java.awt.Color(70, 110, 196));
        CComuna.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CComuna.setForeground(new java.awt.Color(0, 0, 0));
        CComuna.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CPais.setBackground(new java.awt.Color(70, 110, 196));
        CPais.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CPais.setForeground(new java.awt.Color(0, 0, 0));
        CPais.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        GuardarDist.setBackground(new java.awt.Color(204, 204, 204));
        GuardarDist.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        GuardarDist.setText("Guardar");
        GuardarDist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarDistActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Rut:");

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Nombre:");

        jLabel29.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Direccion:");

        jLabel30.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Telefono:");

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Contacto Encargado:");

        NombreDist.setBackground(new java.awt.Color(70, 110, 196));
        NombreDist.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        NombreDist.setForeground(new java.awt.Color(0, 0, 0));

        DirecDist.setBackground(new java.awt.Color(70, 110, 196));
        DirecDist.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        DirecDist.setForeground(new java.awt.Color(0, 0, 0));

        TelefonoDist.setBackground(new java.awt.Color(70, 110, 196));
        TelefonoDist.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        TelefonoDist.setForeground(new java.awt.Color(0, 0, 0));

        ServDist.setBackground(new java.awt.Color(70, 110, 196));
        ServDist.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ServDist.setForeground(new java.awt.Color(0, 0, 0));

        EmailDist.setBackground(new java.awt.Color(70, 110, 196));
        EmailDist.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        EmailDist.setForeground(new java.awt.Color(0, 0, 0));

        ContacDist.setBackground(new java.awt.Color(70, 110, 196));
        ContacDist.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ContacDist.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CPais, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GuardarDist, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel24))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ContacDist, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EmailDist, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ServDist, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TelefonoDist, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DirecDist, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NombreDist, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RutDist, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CComuna, 0, 754, Short.MAX_VALUE))))))
                .addGap(0, 76, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RutDist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(28, 28, 28)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(NombreDist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(DirecDist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(TelefonoDist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ServDist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(27, 27, 27)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailDist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(27, 27, 27)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContacDist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGap(27, 27, 27)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CComuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(27, 27, 27)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(GuardarDist, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        PanelDist.addTab("Gestión de Distribuidores", jPanel9);

        getContentPane().add(PanelDist, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscadorMouseClicked
        Buscador.setText("");
    }//GEN-LAST:event_BuscadorMouseClicked

    private void BuscadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscadorKeyTyped
        LlenarTabla1Dist(Buscador.getText());
    }//GEN-LAST:event_BuscadorKeyTyped

    private void TablaDistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDistMouseClicked
        filaDist=TablaDist.rowAtPoint(evt.getPoint());
    }//GEN-LAST:event_TablaDistMouseClicked

    private void GuardarDistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarDistActionPerformed
        PaisDist Pdist=(PaisDist)CPais.getSelectedItem();
        Comuna com=(Comuna)CComuna.getSelectedItem();
        if (RutDist.getText().equals("") || NombreDist.getText().equals("") || DirecDist.getText().equals("") 
            ||  TelefonoDist.getText().equals("") || ServDist.getText().equals("") || EmailDist.getText().equals("") 
            ||   ContacDist.getText().equals("")  ){
            JOptionPane.showMessageDialog(this, "DEBE INGRESAR TODOS LOS DATOS!!!", "La biblioteca",JOptionPane.OK_OPTION+JOptionPane.INFORMATION_MESSAGE);
            RutDist.grabFocus();
        }else{
            if (sswitch==0) crd.insertarDistribuidores(RutDist.getText(), NombreDist.getText(), DirecDist.getText(), 
                    TelefonoDist.getText(), Integer.parseInt(ServDist.getText()), EmailDist.getText(), ContacDist.getText(), com.getCod_comuna(), Pdist.getCod_pais());
            
            else crd.editarDistribuidores(codDist, RutDist.getText(), NombreDist.getText(), DirecDist.getText(), 
                    TelefonoDist.getText(), Integer.parseInt(ServDist.getText()), EmailDist.getText(), ContacDist.getText(), com.getCod_comuna(), Pdist.getCod_pais());
            PanelDist.setSelectedIndex(1);  
            JOptionPane.showMessageDialog(this, "OPERACION REALIZADA", "LA BIBLIOTECA",JOptionPane.OK_OPTION+JOptionPane.INFORMATION_MESSAGE);   
        }   
        RutDist.setText("");
        NombreDist.setText("");
        DirecDist.setText("");
        TelefonoDist.setText("");
        ServDist.setText("");
        EmailDist.setText("");
        ContacDist.setText("");
        LlenarTabla1Dist("");
        sswitch=0;
      
    }//GEN-LAST:event_GuardarDistActionPerformed

    private void AgregarBoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarBoFActionPerformed
        sswitch=0;
        PanelDist.setSelectedIndex(1);
        RutDist.grabFocus();
    }//GEN-LAST:event_AgregarBoFActionPerformed

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        if (filaDist>-1) {
            codDist=Integer.parseInt(String.valueOf(TablaDist.getValueAt(filaDist, 0)));
            RutDist.setText(String.valueOf(TablaDist.getValueAt(filaDist, 1)));
            NombreDist.setText(String.valueOf(TablaDist.getValueAt(filaDist, 2)));
            DirecDist.setText(String.valueOf(TablaDist.getValueAt(filaDist, 3)));
            TelefonoDist.setText(String.valueOf(TablaDist.getValueAt(filaDist, 4)));
            ServDist.setText(String.valueOf(TablaDist.getValueAt(filaDist, 5)));
            EmailDist.setText(String.valueOf(TablaDist.getValueAt(filaDist, 6)));
            ContacDist.setText(String.valueOf(TablaDist.getValueAt(filaDist, 7)));
            sswitch=1;
            PanelDist.setSelectedIndex(1);
        } else {
           JOptionPane.showMessageDialog(this, "DEBE SELECCIONAR UNA FILA","ADVERTENCIA",JOptionPane.OK_OPTION+JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_EditarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        if (filaDist>-1) {
            int respuesta=JOptionPane.showConfirmDialog(this, "¿REALMENTE DESEA ELEMINAR EL REGISTRO? NO VOLVERA A RECUPERAR EL REGISTRO..."+" "
                    +String.valueOf(TablaDist.getValueAt(filaDist, 2)),"ADVERTENCIA",JOptionPane.YES_NO_OPTION+JOptionPane.WARNING_MESSAGE);
            if (respuesta==0) {
                crd.EliminarDistribuidores(Integer.parseInt(String.valueOf(TablaDist.getValueAt(filaDist, 0))));
                LlenarTabla1Dist("");
                JOptionPane.showMessageDialog(this, "DISTRIBUIDOR ELIMINADO", "LA BIBLIOTECA",JOptionPane.OK_OPTION+JOptionPane.INFORMATION_MESSAGE);
                filaDist=-1;
            }
        } else {
           JOptionPane.showMessageDialog(this, "DEBE SELECCIONAR UNA FILA","ADVERTENCIA",JOptionPane.OK_OPTION+JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_EliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarBoF;
    private javax.swing.JTextField Buscador;
    private javax.swing.JComboBox CComuna;
    private javax.swing.JComboBox CPais;
    private javax.swing.JTextField ContacDist;
    private javax.swing.JTextField DirecDist;
    private javax.swing.JButton Editar;
    private javax.swing.JButton Eliminar;
    private javax.swing.JTextField EmailDist;
    private javax.swing.JButton GuardarDist;
    private javax.swing.JTextField NombreDist;
    private javax.swing.JTabbedPane PanelDist;
    private javax.swing.JTextField RutDist;
    private javax.swing.JTextField ServDist;
    private javax.swing.JTable TablaDist;
    private javax.swing.JTextField TelefonoDist;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JLabel registros;
    // End of variables declaration//GEN-END:variables
}
