/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Control_AutorLibro;
import Modelo.AutorLibro;
import Modelo.Autores;
import Modelo.Libros;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mark-
 */
public class FRM_AutorLibro extends javax.swing.JInternalFrame {
    Control_AutorLibro cra=new Control_AutorLibro();
    DefaultTableModel tabla=new DefaultTableModel();
    
    //tabla de autores en Libros
    public void LlenarTablaAutorLibro(String dato){
    tabla.setColumnCount(0);
        tabla.addColumn("Nombre de Autor");
        tabla.addColumn("Pseudonimo de Autor");
        tabla.addColumn("Titulo de Libro");
        tabla.addColumn("Numero de Paginas");
        tabla.addColumn("Precio de Libro");
        List<AutorLibro> lista=cra.ListarAutorLibro(dato);
        tabla.setNumRows(lista.size());
        for (int i = 0; i < lista.size(); i++) {
            tabla.setValueAt(lista.get(i).getNom_autor(), i, 0);
            tabla.setValueAt(lista.get(i).getPseu_autor(), i, 1);
            tabla.setValueAt(lista.get(i).getTitulo_libro(), i, 2);
            tabla.setValueAt(lista.get(i).getPag_libro(), i, 3);
            tabla.setValueAt(lista.get(i).getPrecio_libro(), i, 4);
        }
        TablaA.setModel(tabla);
    }
    
    //COMBOBOX PARA GESTION DE AUTOR EN LIBROS
    private void ComboAutorEnLibro(){
       DefaultComboBoxModel combo = new DefaultComboBoxModel();
        Control_AutorLibro cal=new Control_AutorLibro();
        List<Autores> lista=cal.ComboBoxAutor();
        for(Autores A:lista){
            A = new Autores(A.getCod_autor(), A.getNom_autor());
            combo.addElement(A);
        }
        ComboAutor.setModel(combo);
    }
    
    private void ComboLibrosAutor(){
       DefaultComboBoxModel combo = new DefaultComboBoxModel();
        Control_AutorLibro ca=new Control_AutorLibro();
        List<Libros> lista=ca.ComboBoxLibros();
        for(Libros L:lista){
            L = new Libros(L.getCod_libro(), L.getTitulo_libro());
            combo.addElement(L);
        }
        ComboLibro.setModel(combo);
    }
    
    public FRM_AutorLibro() {
        initComponents();
        LlenarTablaAutorLibro("");
        ComboAutorEnLibro();
        ComboLibrosAutor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelAl = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jToolBar12 = new javax.swing.JToolBar();
        RegistrosA = new javax.swing.JLabel();
        jToolBar10 = new javax.swing.JToolBar();
        AgregarA = new javax.swing.JButton();
        jSeparator36 = new javax.swing.JToolBar.Separator();
        jSeparator37 = new javax.swing.JToolBar.Separator();
        jLabel40 = new javax.swing.JLabel();
        jSeparator38 = new javax.swing.JToolBar.Separator();
        jSeparator41 = new javax.swing.JToolBar.Separator();
        BuscadorA = new javax.swing.JTextField();
        jSeparator42 = new javax.swing.JToolBar.Separator();
        jScrollPane5 = new javax.swing.JScrollPane();
        TablaA = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        ComboLibro = new javax.swing.JComboBox();
        jLabel50 = new javax.swing.JLabel();
        ComboAutor = new javax.swing.JComboBox();
        GuardarIdiomaLibro1 = new javax.swing.JButton();

        PanelAl.setBackground(new java.awt.Color(153, 153, 153));
        PanelAl.setForeground(new java.awt.Color(0, 0, 0));
        PanelAl.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        PanelAl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jPanel1.setLayout(new java.awt.BorderLayout());

        jToolBar12.setBackground(new java.awt.Color(204, 204, 204));
        jToolBar12.setFloatable(false);
        jToolBar12.setForeground(new java.awt.Color(204, 204, 204));
        jToolBar12.setRollover(true);

        RegistrosA.setForeground(new java.awt.Color(0, 0, 0));
        RegistrosA.setText("jLabel5");
        jToolBar12.add(RegistrosA);

        jPanel1.add(jToolBar12, java.awt.BorderLayout.PAGE_START);

        jToolBar10.setBackground(new java.awt.Color(204, 204, 204));
        jToolBar10.setFloatable(false);
        jToolBar10.setRollover(true);

        AgregarA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/matematicas.png"))); // NOI18N
        AgregarA.setFocusable(false);
        AgregarA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AgregarA.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AgregarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarAActionPerformed(evt);
            }
        });
        jToolBar10.add(AgregarA);
        jToolBar10.add(jSeparator36);
        jToolBar10.add(jSeparator37);

        jLabel40.setText("                                            ");
        jToolBar10.add(jLabel40);
        jToolBar10.add(jSeparator38);
        jToolBar10.add(jSeparator41);

        BuscadorA.setBackground(new java.awt.Color(70, 110, 196));
        BuscadorA.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BuscadorA.setForeground(new java.awt.Color(0, 0, 0));
        BuscadorA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BuscadorA.setText("Buscador");
        BuscadorA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscadorAMouseClicked(evt);
            }
        });
        BuscadorA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BuscadorAKeyTyped(evt);
            }
        });
        jToolBar10.add(BuscadorA);
        jToolBar10.add(jSeparator42);

        jPanel1.add(jToolBar10, java.awt.BorderLayout.PAGE_END);

        TablaA.setBackground(new java.awt.Color(204, 204, 204));
        TablaA.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        TablaA.setForeground(new java.awt.Color(0, 0, 0));
        TablaA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaA.setRowHeight(25);
        jScrollPane5.setViewportView(TablaA);

        jPanel1.add(jScrollPane5, java.awt.BorderLayout.CENTER);

        PanelAl.addTab("Autores en Libros", jPanel1);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel49.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(0, 0, 0));
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("Titulo de Libro:");

        ComboLibro.setBackground(new java.awt.Color(70, 110, 196));
        ComboLibro.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ComboLibro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel50.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(0, 0, 0));
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setText("Autores Disponible:");

        ComboAutor.setBackground(new java.awt.Color(70, 110, 196));
        ComboAutor.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ComboAutor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        GuardarIdiomaLibro1.setBackground(new java.awt.Color(204, 204, 204));
        GuardarIdiomaLibro1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        GuardarIdiomaLibro1.setText("Guardar");
        GuardarIdiomaLibro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarIdiomaLibro1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel49, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 29, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ComboAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComboLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19))
                            .addComponent(jLabel50, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(GuardarIdiomaLibro1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(205, 205, 205))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel49)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ComboLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel50)
                .addGap(12, 12, 12)
                .addComponent(ComboAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(GuardarIdiomaLibro1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        PanelAl.addTab("Gestion", jPanel2);

        getContentPane().add(PanelAl, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarAActionPerformed

        PanelAl.setSelectedIndex(1);
    }//GEN-LAST:event_AgregarAActionPerformed

    private void BuscadorAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscadorAMouseClicked
        BuscadorA.setText("");
    }//GEN-LAST:event_BuscadorAMouseClicked

    private void BuscadorAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscadorAKeyTyped
        LlenarTablaAutorLibro(BuscadorA.getText());
    }//GEN-LAST:event_BuscadorAKeyTyped

    private void GuardarIdiomaLibro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarIdiomaLibro1ActionPerformed
        Libros lib=(Libros)ComboLibro.getSelectedItem();
        Autores aut=(Autores)ComboAutor.getSelectedItem();
        cra.InsertarAutorLibro(aut.getCod_autor(), lib.getCod_libro());
        PanelAl.setSelectedIndex(0);
        JOptionPane.showMessageDialog(this, "OPERACION REALIZADA", "LA BIBLIOTECA",JOptionPane.OK_OPTION+JOptionPane.INFORMATION_MESSAGE);
        LlenarTablaAutorLibro("");
    }//GEN-LAST:event_GuardarIdiomaLibro1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarA;
    private javax.swing.JTextField BuscadorA;
    private javax.swing.JComboBox ComboAutor;
    private javax.swing.JComboBox ComboLibro;
    private javax.swing.JButton GuardarIdiomaLibro1;
    private javax.swing.JTabbedPane PanelAl;
    private javax.swing.JLabel RegistrosA;
    private javax.swing.JTable TablaA;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JToolBar.Separator jSeparator36;
    private javax.swing.JToolBar.Separator jSeparator37;
    private javax.swing.JToolBar.Separator jSeparator38;
    private javax.swing.JToolBar.Separator jSeparator41;
    private javax.swing.JToolBar.Separator jSeparator42;
    private javax.swing.JToolBar jToolBar10;
    private javax.swing.JToolBar jToolBar12;
    // End of variables declaration//GEN-END:variables
}
