/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Controlador.Control_Usuario;
import Modelo.Usuarios;
import java.awt.event.KeyEvent;
import java.util.ArrayList;

/**
 *
 * @author Mark-
 */
public class Login extends javax.swing.JInternalFrame {
    ArrayList<Usuarios> lista;
    
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.lista=lista;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        var1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        BtnI = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        mensaje = new javax.swing.JLabel();
        var2 = new javax.swing.JPasswordField();

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Password:");

        var1.setBackground(new java.awt.Color(70, 110, 196));
        var1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        var1.setForeground(new java.awt.Color(0, 0, 0));
        var1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        var1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                var1KeyPressed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre de Usuario:");

        BtnI.setBackground(new java.awt.Color(255, 255, 255));
        BtnI.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BtnI.setForeground(new java.awt.Color(0, 0, 0));
        BtnI.setText("Iniciar Sesion");
        BtnI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        mensaje.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        mensaje.setForeground(new java.awt.Color(153, 0, 0));
        mensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        var2.setBackground(new java.awt.Color(70, 110, 196));
        var2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        var2.setForeground(new java.awt.Color(0, 0, 0));
        var2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        var2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                var2KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(var1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(43, 43, 43))
                    .addComponent(var2, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnI)
                        .addGap(119, 119, 119))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(98, 98, 98))))
            .addComponent(mensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(var1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(var2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnI)
                .addGap(28, 28, 28)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mensaje)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIActionPerformed
        FRM_Usuarios frmu=new FRM_Usuarios();
        mensaje.setVisible(false);
        Control_Usuario control=new Control_Usuario();
        String pass=String.copyValueOf(var2.getPassword());
        //RECORRER LA LISTA DE USUARIOS
            if (control.login(var1.getText(), pass, "Administrador")) {     //CUMPLE LA COMPARACION EN TRUE TRUE.
            Principal.Nusu.setText("BIENVENIDO ADMINISTRADOR: "+var1.getText());
            Principal.MenuVA.setVisible(true);
            Principal.MenuVA.setEnabled(true);
            
            Principal.MenuGestionP.setVisible(true);
            Principal.MenuGestionP.setEnabled(true);
            
            Principal.MenuU.setVisible(true);
            Principal.MenuU.setEnabled(true);
            
            Principal.MenuC.setVisible(true);
            Principal.MenuC.setEnabled(true);

            frmu.EliminarUsuarios.setEnabled(true);
            
            this.dispose();

            
            
        }else{
            if (control.login(var1.getText(), pass, "Inventario")) {     //CUMPLE LA COMPARACION EN TRUE TRUE.
            Principal.Nusu.setText("BIENVENIDO CONTROL DE INVENTARIO: "+var1.getText());
                Principal.MenuC.setVisible(true);
                Principal.MenuC.setEnabled(true);
   
            this.dispose();
            
            }else{
                if (control.login(var1.getText(), pass, "Vendedor")) {     //CUMPLE LA COMPARACION EN TRUE TRUE.
                    Principal.Nusu.setText("BIENVENIDO VENDEDOR: "+var1.getText());
                    Principal.MenuVA.setVisible(true);
                    Principal.MenuVA.setEnabled(true);
                    this.dispose();
            
                }else{
                    if(control.login(var1.getText(), pass, "Cliente")){
                        Principal.Nusu.setText("BIENVENIDO : "+var1.getText());
                        Principal.MenuCliente.setVisible(true);
                        Principal.MenuCliente.setEnabled(true);
                        this.dispose();
                    }else{
                        var1.setText("");//vacia las casillas de texto al presionar iniciar sesion y este tire error
                        var2.setText("");
                        mensaje.setVisible(true);
                        mensaje.setText("USUARIO O PASSWORD INCORRECTO");//setText para poner un texto en el label
                    }
            }
            
            
            
        }
            }
    }//GEN-LAST:event_BtnIActionPerformed

    private void var1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_var1KeyPressed
       if (evt.getKeyCode()==KeyEvent.VK_ENTER) {//pregunta si el usuario escribe en el textField y si apreta enter, pasa a la siguiente caja de texto
            var1.grabFocus();
        }
    }//GEN-LAST:event_var1KeyPressed

    private void var2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_var2KeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {//pregunta si hay texto y si presiona enter, cuando se cumpla, el boton de inicio de sesion se presionaara con ENTER.
            BtnIActionPerformed(null);
        }
    }//GEN-LAST:event_var2KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel mensaje;
    private javax.swing.JTextField var1;
    private javax.swing.JPasswordField var2;
    // End of variables declaration//GEN-END:variables
}
