/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import java.awt.Dimension;
import javax.swing.DesktopManager;
import javax.swing.JInternalFrame;

/**
 *
 * @author Mark-
 */
public class Principal extends javax.swing.JFrame {

    public static void centrar(JInternalFrame frm) {
        Dimension contenedor=PanelDesktop.getSize();
        Dimension hijo=frm.getSize();
        frm.setLocation((contenedor.width-hijo.width)/2,(contenedor.height-hijo.height)/2);//width es ancho(X) y height es largo(Y).
        frm.show();
    }
    public Principal() {
        initComponents();
        this.setExtendedState(6);
        MenuVA.setVisible(false);
        MenuC.setVisible(false);
        MenuGestionP.setVisible(false);
        MenuU.setVisible(false);
        MenuCliente.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        IniciarSesion = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        CerrarSesion = new javax.swing.JButton();
        toolbar1 = new javax.swing.JToolBar();
        Nusu = new javax.swing.JLabel();
        PanelDesktop = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuVA = new javax.swing.JMenu();
        MenuC = new javax.swing.JMenu();
        MenuGestionP = new javax.swing.JMenu();
        MenuU = new javax.swing.JMenu();
        MenuCliente = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jToolBar1.setBackground(new java.awt.Color(105, 149, 236));
        jToolBar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jToolBar1.setRollover(true);
        jToolBar1.add(jSeparator3);

        IniciarSesion.setText("INICIAR SESION");
        IniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IniciarSesion.setFocusable(false);
        IniciarSesion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        IniciarSesion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        IniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarSesionActionPerformed(evt);
            }
        });
        jToolBar1.add(IniciarSesion);
        jToolBar1.add(jSeparator1);

        CerrarSesion.setText("CERRAR SESION");
        CerrarSesion.setEnabled(false);
        CerrarSesion.setFocusable(false);
        CerrarSesion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CerrarSesion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSesionActionPerformed(evt);
            }
        });
        jToolBar1.add(CerrarSesion);

        jPanel1.add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        toolbar1.setBackground(new java.awt.Color(105, 149, 236));
        toolbar1.setBorder(null);
        toolbar1.setRollover(true);

        Nusu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/social.png"))); // NOI18N
        toolbar1.add(Nusu);

        jPanel1.add(toolbar1, java.awt.BorderLayout.PAGE_END);

        PanelDesktop.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/biblioteca2.png"))); // NOI18N

        PanelDesktop.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout PanelDesktopLayout = new javax.swing.GroupLayout(PanelDesktop);
        PanelDesktop.setLayout(PanelDesktopLayout);
        PanelDesktopLayout.setHorizontalGroup(
            PanelDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDesktopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1536, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelDesktopLayout.setVerticalGroup(
            PanelDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDesktopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        jPanel1.add(PanelDesktop, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 204));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        MenuVA.setText("Ventas y Arriendos");
        MenuVA.setEnabled(false);
        MenuVA.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        MenuVA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuVAMouseClicked(evt);
            }
        });
        jMenuBar1.add(MenuVA);

        MenuC.setText("Compras");
        MenuC.setEnabled(false);
        MenuC.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        MenuC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuCMouseClicked(evt);
            }
        });
        jMenuBar1.add(MenuC);

        MenuGestionP.setText("Gestion Biblioteca");
        MenuGestionP.setEnabled(false);
        MenuGestionP.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        MenuGestionP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuGestionPMouseClicked(evt);
            }
        });
        jMenuBar1.add(MenuGestionP);

        MenuU.setText("Gestion de Usuarios");
        MenuU.setEnabled(false);
        MenuU.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        MenuU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuUMouseClicked(evt);
            }
        });
        jMenuBar1.add(MenuU);

        MenuCliente.setText("Libros en Stock");
        MenuCliente.setEnabled(false);
        MenuCliente.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        MenuCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuClienteMouseClicked(evt);
            }
        });
        jMenuBar1.add(MenuCliente);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesionActionPerformed
        IniciarSesion.setEnabled(true);
        CerrarSesion.setEnabled(false);
        Nusu.setText("");
        
                MenuC.setVisible(false);
                MenuGestionP.setVisible(false);
                MenuU.setVisible(false);
                MenuVA.setVisible(false);
                MenuCliente.setVisible(false);
                
        try{
            //CERRAR TODOS LOS HIJOS ACTIVOS login y galerias
            JInternalFrame frames[]= PanelDesktop.getAllFrames();//se crea un arreglo con el numero de frames del panel Vista
            DesktopManager DeskMan=PanelDesktop.getDesktopManager();//Deksman es una instnacia de jdekstop
            for(JInternalFrame frame:frames){//recorre las posiciones de todos los formularios activos.
                DeskMan.closeFrame(frame);
                frame.setClosed(false);
                IniciarSesion.setEnabled(true);//activa el boton de inicar sesion
                CerrarSesion.setEnabled(false);
                
            }
            //abrir el login
            IniciarSesion.doClick();//hace la accion de gatillo al terminar el rcorrido de los formularios activos. para activar el login.
            
            
        }catch(Exception err){
        }
                
               
        Nusu.setText("");
    }//GEN-LAST:event_CerrarSesionActionPerformed

    private void IniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarSesionActionPerformed
        Login Formulario=new Login();//crear hijo de login llamado formulario.
        if (verificar(Formulario)) {
            PanelDesktop.add(Formulario);//le dice a Formulario donde tiene que estar.
        centrar(Formulario);
        IniciarSesion.setEnabled(false);//activa el botonde inicar sesion
        CerrarSesion.setEnabled(true);
        }else
            Formulario.dispose();
    }//GEN-LAST:event_IniciarSesionActionPerformed

    private void MenuCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuCMouseClicked
        //lanzar formulario de administrador
            Compras compras= new Compras();
            Principal.PanelDesktop.add(compras);
                try {
                    compras.setMaximum(true);
                } catch (Exception e) {
                    System.out.println("ERROR: "+e);
                }
            compras.show();
    }//GEN-LAST:event_MenuCMouseClicked

    private void MenuVAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuVAMouseClicked
        Ventas_y_Arriendos ventasArriendo= new Ventas_y_Arriendos();
            Principal.PanelDesktop.add(ventasArriendo);
                try {
                    ventasArriendo.setMaximum(true);
                } catch (Exception e) {
                    System.out.println("ERROR: "+e);
                }
            ventasArriendo.show();
    }//GEN-LAST:event_MenuVAMouseClicked

    private void MenuGestionPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuGestionPMouseClicked
        Gestion_Personas tc=new Gestion_Personas();
        Principal.PanelDesktop.add(tc);
        try {
            tc.setMaximum(true);
        } catch (Exception e) {
            System.out.println("Error "+e);
        }
        tc.show();
    }//GEN-LAST:event_MenuGestionPMouseClicked

    private void MenuUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuUMouseClicked
        FRM_Usuarios frmu=new FRM_Usuarios();
        Principal.PanelDesktop.add(frmu);
        Principal.centrar(frmu);
        
    }//GEN-LAST:event_MenuUMouseClicked

    private void MenuClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuClienteMouseClicked
        StockLibros st=new StockLibros();
        Principal.PanelDesktop.add(st);
        try {
            st.setMaximum(true);
        } catch (Exception e) {
            System.out.println("Error "+e);
        }
        st.show();
    }//GEN-LAST:event_MenuClienteMouseClicked

    public boolean verificar (JInternalFrame login ){
        //variable para determinar el estado de login a crear
        boolean estado=true;
        //recorre el contenedor para determinar las instancias abiertas de login
        for (int i = 0; i < PanelDesktop.getComponentCount(); i++) {
            if(login.getClass().isInstance(PanelDesktop.getComponent(i))){//si la clase que instancio al objeto de login es la instancia del japenel el estado es falso 
                //se encuentra ellogin abierto
                estado=false;
            }
        }
        return !login.isShowing()&& estado;//si el login no se esta mostrando y el estado es falso, retorna un verdadero.
        //si es false y estado es verdadero, se retorna verdadero
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CerrarSesion;
    private javax.swing.JButton IniciarSesion;
    public static javax.swing.JMenu MenuC;
    public static javax.swing.JMenu MenuCliente;
    public static javax.swing.JMenu MenuGestionP;
    public static javax.swing.JMenu MenuU;
    public static javax.swing.JMenu MenuVA;
    public static javax.swing.JLabel Nusu;
    public static javax.swing.JDesktopPane PanelDesktop;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar toolbar1;
    // End of variables declaration//GEN-END:variables
}
